//
// ExerciseCatalogAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ExerciseCatalogAPI {

    /**
     Listar o catálogo canônico de exercícios para autoria do personal

     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter query: (query) Busca textual opcional; texto em branco equivale a ausência de filtro. (optional)
     - parameter cursor: (query) Cursor opaco da página anterior; nunca é offset nem ID interpretável pelo cliente. (optional)
     - parameter limit: (query) Tamanho solicitado; padrão 50, máximo 100. (optional, default to 50)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listExerciseCatalog(acceptLanguage: String? = nil, query: String? = nil, cursor: String? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: ExerciseCatalogPage?, _ error: Error?) -> Void)) -> RequestTask {
        return listExerciseCatalogWithRequestBuilder(acceptLanguage: acceptLanguage, query: query, cursor: cursor, limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Listar o catálogo canônico de exercícios para autoria do personal
     - GET /exercises
     - Coleção autenticada e exclusiva do papel PERSONAL. A busca cobre nome do exercício, nome da variante, grupo muscular e contexto de equipamento. A paginação usa cursor opaco e ordem estável definida pelo servidor. O contrato nunca expõe nome, ID, payload ou credencial de provider. A mídia está ligada à ExerciseVariant; sua ausência não impede prescrever ou executar o exercício. `assetId + mediaVersion`, e nunca a URL de entrega, formam a identidade estável para cache. `expiresAt` expira apenas a URL; `offlineValidUntil` limita o direito de retenção offline e possui semântica independente.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale), Vary(String)]
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter query: (query) Busca textual opcional; texto em branco equivale a ausência de filtro. (optional)
     - parameter cursor: (query) Cursor opaco da página anterior; nunca é offset nem ID interpretável pelo cliente. (optional)
     - parameter limit: (query) Tamanho solicitado; padrão 50, máximo 100. (optional, default to 50)
     - returns: RequestBuilder<ExerciseCatalogPage>
     */
    open class func listExerciseCatalogWithRequestBuilder(acceptLanguage: String? = nil, query: String? = nil, cursor: String? = nil, limit: Int? = nil) -> RequestBuilder<ExerciseCatalogPage> {
        let localVariablePath = "/exercises"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query?.encodeToJSON(), isExplode: true),
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ExerciseCatalogPage>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
