//
// PersonalProfileAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PersonalProfileAPI {

    /**
     Confirmar o envio do avatar profissional

     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter uploadId: (path) Intenção de envio aberta por &#x60;POST /personal/profile/avatar/upload-intents&#x60; e pertencente ao personal autenticado.
     - parameter completePersonalAvatarUploadRequest: (body)
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func completePersonalAvatarUpload(idempotencyKey: String, uploadId: String, completePersonalAvatarUploadRequest: CompletePersonalAvatarUploadRequest, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: AvatarView?, _ error: Error?) -> Void)) -> RequestTask {
        return completePersonalAvatarUploadWithRequestBuilder(idempotencyKey: idempotencyKey, uploadId: uploadId, completePersonalAvatarUploadRequest: completePersonalAvatarUploadRequest, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Confirmar o envio do avatar profissional
     - POST /personal/profile/avatar/upload-intents/{uploadId}/complete
     - Segundo passo do ciclo. Confirma, de forma idempotente, que os bytes descritos pela intenção foram entregues, e é a única forma de o avatar passar a existir: sem esta confirmação o PUT não muda estado algum de produto. O servidor reconfere tamanho, formato e checksum antes de aceitar, e só então publica `assetId` + `mediaVersion` com `origin: USER_UPLOAD`. O processamento dos derivados é assíncrono no servidor e online-only: a resposta pode sair como `PROCESSING` e o resultado do antivírus/scan aparece depois como `state: READY` ou `state: REJECTED` com `rejectionReason`. Não existe outbox de bytes no cliente e nenhuma jornada depende de fila offline. Confirmar a mesma intenção com a mesma `Idempotency-Key` e o mesmo corpo devolve a projeção original sem reprocessar; a mesma chave com corpo divergente responde `409 IDEMPOTENCY_CONFLICT`. Uma intenção vencida responde `410` e exige um novo ciclo. Uma intenção inexistente e uma intenção de outra pessoa respondem de forma indistinguível, para não revelar existência fora do escopo do ator.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale), Vary(String), Cache-Control(String)]
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter uploadId: (path) Intenção de envio aberta por &#x60;POST /personal/profile/avatar/upload-intents&#x60; e pertencente ao personal autenticado.
     - parameter completePersonalAvatarUploadRequest: (body)
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<AvatarView>
     */
    open class func completePersonalAvatarUploadWithRequestBuilder(idempotencyKey: String, uploadId: String, completePersonalAvatarUploadRequest: CompletePersonalAvatarUploadRequest, acceptLanguage: String? = nil) -> RequestBuilder<AvatarView> {
        var localVariablePath = "/personal/profile/avatar/upload-intents/{uploadId}/complete"
        let uploadIdPreEscape = "\(APIHelper.mapValueToPathItem(uploadId))"
        let uploadIdPostEscape = uploadIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{uploadId}", with: uploadIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: completePersonalAvatarUploadRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Accept-Language": acceptLanguage?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AvatarView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Abrir uma intenção de envio do avatar profissional

     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter createPersonalAvatarUploadIntentRequest: (body)
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPersonalAvatarUploadIntent(idempotencyKey: String, createPersonalAvatarUploadIntentRequest: CreatePersonalAvatarUploadIntentRequest, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: PersonalAvatarUploadIntentView?, _ error: Error?) -> Void)) -> RequestTask {
        return createPersonalAvatarUploadIntentWithRequestBuilder(idempotencyKey: idempotencyKey, createPersonalAvatarUploadIntentRequest: createPersonalAvatarUploadIntentRequest, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Abrir uma intenção de envio do avatar profissional
     - POST /personal/profile/avatar/upload-intents
     - Primeiro passo do ciclo do avatar profissional. O cliente declara tipo, tamanho e checksum dos bytes que pretende enviar, e o servidor devolve uma intenção de envio de curta duração: `uploadId`, um PUT temporário, os cabeçalhos obrigatórios daquele PUT e o instante de expiração. O contrato é provider-neutral: a intenção nunca expõe bucket, chave de objeto, KMS, ARN, credencial ou topologia de armazenamento, e a URL devolvida é uma capacidade efêmera de escrita — **nunca** identidade do avatar. A identidade é `assetId` + `mediaVersion`, publicada em `AvatarView`. Abrir intenção não altera o avatar vigente: enquanto o ciclo não é confirmado, `AvatarView` continua exatamente como estava. O replay da mesma `Idempotency-Key` com o mesmo corpo devolve a intenção original sem emitir outra; a mesma chave com corpo divergente responde `409 IDEMPOTENCY_CONFLICT`. O tratamento de bytes é online-only: não existe outbox nem fila offline de mídia, e nenhum `commandType` de sync transporta avatar.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale), Vary(String), Cache-Control(String)]
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter createPersonalAvatarUploadIntentRequest: (body)
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<PersonalAvatarUploadIntentView>
     */
    open class func createPersonalAvatarUploadIntentWithRequestBuilder(idempotencyKey: String, createPersonalAvatarUploadIntentRequest: CreatePersonalAvatarUploadIntentRequest, acceptLanguage: String? = nil) -> RequestBuilder<PersonalAvatarUploadIntentView> {
        let localVariablePath = "/personal/profile/avatar/upload-intents"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createPersonalAvatarUploadIntentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Accept-Language": acceptLanguage?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PersonalAvatarUploadIntentView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remover o avatar profissional

     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePersonalAvatar(idempotencyKey: String, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePersonalAvatarWithRequestBuilder(idempotencyKey: idempotencyKey, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Remover o avatar profissional
     - DELETE /personal/profile/avatar
     - Remove o avatar do personal autenticado de forma idempotente. A remoção grava um tombstone: o `assetId` anterior deixa de resolver, as variantes temporárias já emitidas deixam de ser renovadas e nenhuma nova leitura do asset removido é autorizada. Depois da remoção `AvatarView` publica `state: NONE` e o cliente cai para as iniciais do nome. A remoção **não ressuscita o Google**: um login posterior com Google não reimporta a foto, e trazer a foto de volta exige um ato explícito — novo envio ou nova chamada de `POST /personal/profile/avatar/import-google`. A resposta é `204`: depois de removido o avatar não existe, e projetá-lo de volta contradiria a própria remoção. Repetir a remoção responde `204` outra vez, sem novo efeito e sem criar `mediaVersion`.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale)]
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<Void>
     */
    open class func deletePersonalAvatarWithRequestBuilder(idempotencyKey: String, acceptLanguage: String? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/personal/profile/avatar"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Obter o Perfil do Personal autenticado

     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPersonalProfile(acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: PersonalProfileView?, _ error: Error?) -> Void)) -> RequestTask {
        return getPersonalProfileWithRequestBuilder(acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Obter o Perfil do Personal autenticado
     - GET /personal/profile
     - Projeção completa do Perfil do Personal **autenticado**, e somente dele: nome de apresentação, avatar, registro profissional autodeclarado, e-mail de acesso somente leitura, provider da sessão, elegibilidade para convidar, especialidades, modo de trabalho, preferências e o resumo da carteira de relacionamentos. Esta é a **única leitura** do contrato que projeta `AvatarView`, e por isso é o caminho de **poll** e de **reemissão** do ciclo publicado em 0.20.0: sem ela `state: PROCESSING` não teria onde ser consultado, `REJECTED` e `NONE` seriam inobserváveis e as variantes temporárias expirariam sem forma de reemissão. Cada leitura devolve variantes novas, com nova expiração; a identidade da mídia continua sendo o par `assetId` + `mediaVersion`, nunca a URL. Os quatro `PUT /personal/onboarding/{profile|specialties|work-style|preferences}` **permanecem válidos depois de `COMPLETED`** e seguem sendo os únicos commands de edição do Perfil: esta versão **não** cria command concorrente e não existe pré-condição de estado que os desative. O `revision` publicado aqui é exatamente o valor que o `If-Match` daqueles commands exige, e o `ETag` desta leitura é esse mesmo validador. `professionalRegistrationStatus` deriva **apenas** da presença de número + UF. Não existe validação externa, não existe selo e o contrato nunca afirma regularidade da pessoa em conselho profissional. O e-mail é **somente leitura**: nenhum request de edição publicado neste contrato transporta e-mail. Audiência: esta projeção é da própria pessoa. O que o **aluno** enxerga do personal permanece limitado a nome, avatar e CREF informado — nunca e-mail, cidade, especialidades, modo de trabalho, preferências ou contadores.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [ETag(String), Content-Language(Locale), Vary(String), Cache-Control(String)]
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<PersonalProfileView>
     */
    open class func getPersonalProfileWithRequestBuilder(acceptLanguage: String? = nil) -> RequestBuilder<PersonalProfileView> {
        let localVariablePath = "/personal/profile"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PersonalProfileView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Importar o avatar profissional da identidade Google autenticada

     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func importPersonalAvatarFromGoogle(idempotencyKey: String, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: AvatarView?, _ error: Error?) -> Void)) -> RequestTask {
        return importPersonalAvatarFromGoogleWithRequestBuilder(idempotencyKey: idempotencyKey, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Importar o avatar profissional da identidade Google autenticada
     - POST /personal/profile/avatar/import-google
     - Importa a foto de perfil **somente** a partir da identidade Google já autenticada da própria conta. A operação **não tem corpo de requisição**: não existe campo de URL, de origem alternativa nem de identificador externo, para que não haja como pedir ao servidor que busque uma imagem arbitrária. `USER_UPLOAD` prevalece: se o avatar vigente veio de envio manual, a importação responde `409 AVATAR_USER_UPLOAD_PRECEDENCE` e nada é sobrescrito. Um login posterior com Google nunca dispara esta operação implicitamente e nunca ressuscita um avatar removido. A indisponibilidade do provedor nunca bloqueia login nem onboarding: a falha é local a esta operação e o cliente segue com as iniciais do nome. Os bytes trazidos passam pelo mesmo scan do envio manual; quando o resultado é conhecido de forma síncrona, a rejeição é tipada em `422 AVATAR_REJECTED_BY_SCAN`. Repetir a importação com a mesma `Idempotency-Key` devolve a projeção original sem criar outra `mediaVersion`.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale), Vary(String), Cache-Control(String)]
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<AvatarView>
     */
    open class func importPersonalAvatarFromGoogleWithRequestBuilder(idempotencyKey: String, acceptLanguage: String? = nil) -> RequestBuilder<AvatarView> {
        let localVariablePath = "/personal/profile/avatar/import-google"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AvatarView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
