//
// StudentOnboardingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StudentOnboardingAPI {

    /**
     Concluir a anamnese funcional, fixando uma versão concluída imutável

     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter ifMatch: (header) ETag exata da revisão lida pelo cliente; impede last-write-wins.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func completeStudentOnboarding(idempotencyKey: String, ifMatch: String, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: StudentOnboardingCompletionView?, _ error: Error?) -> Void)) -> RequestTask {
        return completeStudentOnboardingWithRequestBuilder(idempotencyKey: idempotencyKey, ifMatch: ifMatch, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Concluir a anamnese funcional, fixando uma versão concluída imutável
     - POST /student/onboarding/complete
     - Transforma o rascunho privado vigente em uma **versão concluída imutável**, com `If-Match` obrigatório, ecoando a mesma e única revisão desta superfície — `anamnesis.draft.revision`, publicada como `ETag` na leitura. Concluir **cria versão**; editar depois e concluir de novo cria **outra** versão e **preserva** a anterior, que continua consultável. Nenhuma versão é reescrita, apagada ou substituída em silêncio. A idempotência é **por versão, não por aluno**: repetir a mesma tentativa sobre a mesma `revision` devolve a mesma versão em vez de criar outra, e portanto produz no máximo uma notificação por versão concluída. A entrega real ao personal **não** é pós-condição desta operação e não é afirmada por ela. **Resposta canônica única, sem ramificação por idade.** Menor e adulto concluem exatamente da mesma forma. Triagem de prontidão pendente e autorização de responsável ausente **não** impedem concluir: elas aparecem apenas como motivos nomeados e acumuláveis em `prescriptionEligibility`. Não existe, aqui, resposta de \"conclusão pendente por responsável\", nem operação de autorização embutida. Concluir afirma que existe versão concluída; **não** afirma elegibilidade para prescrição.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale), Vary(String)]
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter ifMatch: (header) ETag exata da revisão lida pelo cliente; impede last-write-wins.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<StudentOnboardingCompletionView>
     */
    open class func completeStudentOnboardingWithRequestBuilder(idempotencyKey: String, ifMatch: String, acceptLanguage: String? = nil) -> RequestBuilder<StudentOnboardingCompletionView> {
        let localVariablePath = "/student/onboarding/complete"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey.encodeToJSON(),
            "If-Match": ifMatch.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StudentOnboardingCompletionView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Ler, como personal do vínculo, o estado e as versões concluídas da anamnese do aluno

     - parameter studentId: (path) Aluno do vínculo ativo do personal autenticado.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPersonalStudentAnamnesis(studentId: String, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: PersonalStudentAnamnesisView?, _ error: Error?) -> Void)) -> RequestTask {
        return getPersonalStudentAnamnesisWithRequestBuilder(studentId: studentId, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Ler, como personal do vínculo, o estado e as versões concluídas da anamnese do aluno
     - GET /personal/students/{studentId}/anamnesis
     - Leitura sem efeito colateral, autorizada somente ao personal do vínculo ativo. **Antes da primeira conclusão a resposta é apenas estado.** `anamnesisState` vale `IN_PROGRESS` e nenhum conteúdo do rascunho é projetado: sem respostas, sem resumo, sem contagem e sem percentual por seção. **Depois da primeira conclusão** a resposta carrega a última versão concluída e a lista das versões anteriores, com data. Uma edição em curso do aluno é invisível aqui e **não** devolve o estado a \"em andamento\": o personal continua vendo a última versão concluída até que outra seja concluída. A operação existe porque a leitura profissional não cabe, de modo compatível, na projeção do próprio aluno: o ator, a autorização e o recorte projetado são outros, e colapsá-los exporia rascunho privado. Ela **não** expõe identidade, nome ou contato de responsável, **não** oferece caminho para conceder, revogar ou consultar autorização de responsável e **não** registra liberação médica ou dispensa: essas superfícies não têm contrato nesta fatia. A autorização de responsável aparece exclusivamente como motivo nomeado em `prescriptionEligibility`. Um aluno inexistente e um aluno de outra relação respondem de forma indistinguível.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [Content-Language(Locale), Vary(String)]
     - parameter studentId: (path) Aluno do vínculo ativo do personal autenticado.
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<PersonalStudentAnamnesisView>
     */
    open class func getPersonalStudentAnamnesisWithRequestBuilder(studentId: String, acceptLanguage: String? = nil) -> RequestBuilder<PersonalStudentAnamnesisView> {
        var localVariablePath = "/personal/students/{studentId}/anamnesis"
        let studentIdPreEscape = "\(APIHelper.mapValueToPathItem(studentId))"
        let studentIdPostEscape = studentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{studentId}", with: studentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PersonalStudentAnamnesisView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Ler a entrada do aluno — onboarding, anamnese funcional, prontidão e elegibilidade

     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getStudentOnboarding(acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: StudentOnboardingView?, _ error: Error?) -> Void)) -> RequestTask {
        return getStudentOnboardingWithRequestBuilder(acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Ler a entrada do aluno — onboarding, anamnese funcional, prontidão e elegibilidade
     - GET /student/onboarding
     - Projeção autenticada do próprio aluno. Publica **quatro estados distintos e não derivados um do outro**: estado do onboarding, `anamnesis.completed` (verdadeiro somente quando existe ao menos uma versão concluída), prontidão e `prescriptionEligibility`. Nenhum cliente calcula elegibilidade, idade, exigência de autorização de responsável ou prontidão a partir dos demais campos. O `anamnesis.draft` devolvido aqui é **privado do aluno**: ele existe para retomar o preenchimento. Ele nunca é projetado para o personal, em conteúdo, resumo, contagem ou percentual. **O `ETag` desta resposta é o validador do rascunho**, idêntico a `anamnesis.draft.revision`, e é exatamente o valor que `If-Match` ecoa nas duas mutações da anamnese: o par `GET` → `If-Match` da convenção HTTP funciona sem tradução. Ele **não** valida a projeção inteira, e por isso esta operação não oferece `If-None-Match` nem `304`: aqui o `ETag` é precondição, não cache. Não existe uma segunda revisão nesta superfície. Nenhum campo desta resposta representa estado de sincronização, fila local ou conectividade.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [ETag(String), Content-Language(Locale), Vary(String)]
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<StudentOnboardingView>
     */
    open class func getStudentOnboardingWithRequestBuilder(acceptLanguage: String? = nil) -> RequestBuilder<StudentOnboardingView> {
        let localVariablePath = "/student/onboarding"
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Accept-Language": acceptLanguage?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StudentOnboardingView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Salvar uma seção tipada da anamnese no rascunho privado do aluno

     - parameter sectionKey: (path) Seção endereçada. &#x60;PUT&#x60; substitui **somente** esta seção do rascunho; as demais permanecem exatamente como estavam. O &#x60;sectionKey&#x60; do corpo seleciona o membro tipado do &#x60;oneOf&#x60; e precisa ser igual a este segmento: divergir é &#x60;422 ANAMNESIS_SECTION_KEY_MISMATCH&#x60;, nunca escrita na seção errada.
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter ifMatch: (header) ETag exata da revisão lida pelo cliente; impede last-write-wins.
     - parameter saveStudentAnamnesisSectionRequest: (body)
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func saveStudentAnamnesisSection(sectionKey: StudentAnamnesisSectionKey, idempotencyKey: String, ifMatch: String, saveStudentAnamnesisSectionRequest: SaveStudentAnamnesisSectionRequest, acceptLanguage: String? = nil, apiResponseQueue: DispatchQueue = FitAppClientSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: StudentAnamnesisDraftView?, _ error: Error?) -> Void)) -> RequestTask {
        return saveStudentAnamnesisSectionWithRequestBuilder(sectionKey: sectionKey, idempotencyKey: idempotencyKey, ifMatch: ifMatch, saveStudentAnamnesisSectionRequest: saveStudentAnamnesisSectionRequest, acceptLanguage: acceptLanguage).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Salvar uma seção tipada da anamnese no rascunho privado do aluno
     - PUT /student/onboarding/anamnesis/{sectionKey}
     - Grava uma seção da anamnese funcional no **rascunho privado** do aluno. Salvar **não** conclui, **não** cria versão e **não** notifica o personal; antes da primeira conclusão o personal vê somente o fato de haver anamnese em andamento. **Não existe `answers` genérico.** O corpo carrega `section`, um `oneOf` discriminado por `sectionKey`, e cada membro fecha o próprio conteúdo com `additionalProperties: false`: uma seção sem membro publicado não é aceita por este contrato. A escrita é compare-and-set: `If-Match` com a revisão do rascunho — publicada tanto em `anamnesis.draft.revision` quanto no `ETag` da leitura, que são o mesmo valor — é obrigatório e duas edições concorrentes **nunca** aplicam last-write-wins — a perdedora recebe `412 PRECONDITION_FAILED` e o rascunho do servidor permanece exatamente como estava. A seção de **triagem de prontidão** (`READINESS_SCREENING` e o seu desdobramento) tem base própria de segurança da prestação do serviço: ela **não** tem pré-condição de consentimento destacado e **não** existe família de erro de consentimento nesta operação. Uma resposta positiva na triagem **não** impede continuar nem concluir; ela altera apenas a prontidão e a elegibilidade para prescrição. O contrato publica apenas a **chave** de cada pergunta do instrumento e a versão aplicada; a redação licenciada do instrumento não trafega por este contrato.
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - responseHeaders: [ETag(String), Content-Language(Locale), Vary(String)]
     - parameter sectionKey: (path) Seção endereçada. &#x60;PUT&#x60; substitui **somente** esta seção do rascunho; as demais permanecem exatamente como estavam. O &#x60;sectionKey&#x60; do corpo seleciona o membro tipado do &#x60;oneOf&#x60; e precisa ser igual a este segmento: divergir é &#x60;422 ANAMNESIS_SECTION_KEY_MISMATCH&#x60;, nunca escrita na seção errada.
     - parameter idempotencyKey: (header) Chave opaca gerada pelo cliente para uma tentativa lógica de mutação.
     - parameter ifMatch: (header) ETag exata da revisão lida pelo cliente; impede last-write-wins.
     - parameter saveStudentAnamnesisSectionRequest: (body)
     - parameter acceptLanguage: (header) Preferência conforme RFC 9110. Canonicalizar tags BCP 47; descartar item inválido ou q&#x3D;0; ordenar por q decrescente e primeira posição no empate; consolidar duplicatas pela maior preferência e primeira posição associada a ela; selecionar somente match exato em {pt-BR, en-US}. pt, en, pt-PT e en-GB não implicam região. Wildcard elegível, ausência, valor integralmente inválido ou falta de match resolvem para pt-BR. Influencia somente server_localized e formatação autorizada; nunca altera client_owned, editorial, authored_preserved ou machine_code. (optional)
     - returns: RequestBuilder<StudentAnamnesisDraftView>
     */
    open class func saveStudentAnamnesisSectionWithRequestBuilder(sectionKey: StudentAnamnesisSectionKey, idempotencyKey: String, ifMatch: String, saveStudentAnamnesisSectionRequest: SaveStudentAnamnesisSectionRequest, acceptLanguage: String? = nil) -> RequestBuilder<StudentAnamnesisDraftView> {
        var localVariablePath = "/student/onboarding/anamnesis/{sectionKey}"
        let sectionKeyPreEscape = "\(APIHelper.mapValueToPathItem(sectionKey))"
        let sectionKeyPostEscape = sectionKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{sectionKey}", with: sectionKeyPostEscape, options: .literal, range: nil)
        let localVariableURLString = FitAppClientSwiftAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: saveStudentAnamnesisSectionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Accept-Language": acceptLanguage?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey.encodeToJSON(),
            "If-Match": ifMatch.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StudentAnamnesisDraftView>.Type = FitAppClientSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
