//
// AccountContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Capacidade que a conta **já detém**, registrada no servidor no momento em que nasceu do ato que a criou. &#x60;STUDENT&#x60; nasce do aceite de um convite que criou a relação; &#x60;PERSONAL&#x60; nasce da conclusão do onboarding profissional. Nenhuma delas é escrita por autenticar, por carregar convite ou por escolher jornada, e nenhuma é derivada do provedor de identidade usado no login. As duas coexistem na mesma conta sem se excluir. O cliente tolera valores futuros desconhecidos e não os promove a papel de navegação. */
public enum AccountContext: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case student = "STUDENT"
    case personal = "PERSONAL"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AccountContext: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
