//
// AccountLinkingChallengeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Desafio de posse do endereço da conta alvo. **Não publica o código**, **não publica o endereço em claro**, nem mesmo mascarado, e **não publica quantas tentativas restam**: revelar o saldo transformaria o limite em oráculo, e mascarar o endereço de outra pessoa já seria confirmar que ela existe — que é o vetor de reivindicação maliciosa que este protocolo fecha. **Os parâmetros são do servidor.** &#x60;expiresAt&#x60;, &#x60;resendAvailableAt&#x60; e &#x60;maxAttempts&#x60; chegam prontos, como instantes e limites absolutos; nenhum cliente embute, calcula ou adivinha validade, janela de reenvio ou limite de tentativas, e o tempo exibido é o que o servidor devolveu, nunca um cronômetro local. Na ausência do dado o cliente falha fechado. Esta é a forma de &#x60;InvitationEmailOwnershipChallengeView&#x60;, que é o desafio de **posse** que a plataforma já emite — e não a de &#x60;OtpChallengeResponse&#x60;, que projeta um desafio de **autenticação**. A exceção é &#x60;destinationHint&#x60;, herdada da família de identidade justamente porque precisa ser uniforme e não confirmar existência. */
public struct AccountLinkingChallengeResponse: Codable, JSONEncodable, Hashable {

    public static let challengeIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let maxAttemptsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var challengeId: String
    /** Fim da validade do desafio, servido pelo servidor. */
    public var expiresAt: Date
    /** Instante a partir do qual pedir outro código deixa de ser recusado. Servido pelo servidor; nunca um cronômetro local. Pedir antes dele responde `429` e **não invalida** o código já enviado. */
    public var resendAvailableAt: Date
    /** Limite de tentativas do desafio, servido para que nenhum app o embuta. O saldo restante **não** é publicado. */
    public var maxAttempts: Int
    /** Dica mascarada e uniforme, nunca confirmação de existência de conta. */
    public var destinationHint: String

    public init(challengeId: String, expiresAt: Date, resendAvailableAt: Date, maxAttempts: Int, destinationHint: String) {
        self.challengeId = challengeId
        self.expiresAt = expiresAt
        self.resendAvailableAt = resendAvailableAt
        self.maxAttempts = maxAttempts
        self.destinationHint = destinationHint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challengeId
        case expiresAt
        case resendAvailableAt
        case maxAttempts
        case destinationHint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challengeId, forKey: .challengeId)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(resendAvailableAt, forKey: .resendAvailableAt)
        try container.encode(maxAttempts, forKey: .maxAttempts)
        try container.encode(destinationHint, forKey: .destinationHint)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension AccountLinkingChallengeResponse: CustomStringConvertible {
    public var description: String { "AccountLinkingChallengeResponse([REDACTED])" }
}
