//
// ApiVersionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiVersionView: Codable, JSONEncodable, Hashable {

    public enum ApiVersion: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case v1 = "v1"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum Consumers: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case backend = "BACKEND"
        case android = "ANDROID"
        case ios = "IOS"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let contractVersionRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]+\\.[0-9]+\\.[0-9]+$/")
    public static let minimumCompatibleContractVersionRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]+\\.[0-9]+\\.[0-9]+$/")
    public static let consumersRule = ArrayRule(minItems: 3, maxItems: nil, uniqueItems: true)
    /** Major version presente no base path público. */
    public var apiVersion: ApiVersion
    /** Versão semântica da especificação atualmente servida. */
    public var contractVersion: String
    /** Menor versão do contrato que os consumidores listados devem compreender. */
    public var minimumCompatibleContractVersion: String
    /** Componentes cobertos pela baseline de compatibilidade. */
    public var consumers: Set<Consumers>

    public init(apiVersion: ApiVersion, contractVersion: String, minimumCompatibleContractVersion: String, consumers: Set<Consumers>) {
        self.apiVersion = apiVersion
        self.contractVersion = contractVersion
        self.minimumCompatibleContractVersion = minimumCompatibleContractVersion
        self.consumers = consumers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiVersion
        case contractVersion
        case minimumCompatibleContractVersion
        case consumers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(apiVersion, forKey: .apiVersion)
        try container.encode(contractVersion, forKey: .contractVersion)
        try container.encode(minimumCompatibleContractVersion, forKey: .minimumCompatibleContractVersion)
        try container.encode(consumers, forKey: .consumers)
    }
}


extension ApiVersionView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if apiVersion == .unknownDefaultOpenApi { return true }

        if consumers.contains(.unknownDefaultOpenApi) { return true }

        return false
    }
}
