//
// AvatarOrigin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Origem do avatar vigente. &#x60;USER_UPLOAD&#x60; **prevalece** sobre &#x60;GOOGLE_IMPORT&#x60;: havendo envio manual, a importação do Google responde &#x60;409 AVATAR_USER_UPLOAD_PRECEDENCE&#x60; e nada é sobrescrito. Um login posterior com Google não reimporta nada e não ressuscita avatar removido. */
public enum AvatarOrigin: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case userUpload = "USER_UPLOAD"
    case googleImport = "GOOGLE_IMPORT"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AvatarOrigin: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
