//
// CalculatedLoadTargetState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Por que o alvo de carga de uma série em percentual existe ou não. &#x60;CALCULATED&#x60;: o personal confirmou uma carga de referência para a variante prescrita e o valor calculado está em &#x60;loadValue&#x60; e &#x60;loadUnit&#x60;. &#x60;NO_CONFIRMED_REFERENCE&#x60;: não havia referência confirmada naquela variante no início da sessão, o alvo de carga fica **ausente** e vale a regra de valor inicial da execução — a estimativa sugerida nunca é referência. &#x60;BELOW_ROUNDING_STEP&#x60;: há referência, mas referência × percentual arredondaria para zero (menos que meio múltiplo de 1 kg ou de 2,5 lb); zero não é carga, e o alvo de carga fica **ausente**. Nenhum dos dois últimos é representado por &#x60;0 kg&#x60;. */
public enum CalculatedLoadTargetState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case calculated = "CALCULATED"
    case noConfirmedReference = "NO_CONFIRMED_REFERENCE"
    case belowRoundingStep = "BELOW_ROUNDING_STEP"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension CalculatedLoadTargetState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
