//
// ComparisonStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado da comparabilidade, sempre explícito. &#x60;COMPARED&#x60;: existe histórico na mesma chave exercício+variante+contexto de equipamento. &#x60;NOT_COMPARABLE&#x60;: existe execução do exercício, porém em variante ou contexto de equipamento que não comparam com este. &#x60;NO_COMPARABLE_EXECUTION&#x60;: primeira execução nesta chave, ainda sem histórico. Nenhum dos dois últimos é representado por zero, por contagem zero ou por omissão do delta. */
public enum ComparisonStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case compared = "COMPARED"
    case notComparable = "NOT_COMPARABLE"
    case noComparableExecution = "NO_COMPARABLE_EXECUTION"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ComparisonStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
