//
// CompletePersonalOnboardingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompletePersonalOnboardingRequest: Codable, JSONEncodable, Hashable {

    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var revision: String

    public init(revision: String) {
        self.revision = revision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revision, forKey: .revision)
    }
}
