//
// ConsentAcceptanceSyncView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** &#x60;view&#x60; fechada de &#x60;CONSENT_ACCEPTANCE&#x60;. O único fato observável é que a versão declarada de um termo identificado foi aceita: nunca o conteúdo do termo, o texto aceito, o dispositivo, o endereço de rede ou o histórico de aceites anteriores. Um aceite novo não sobrescreve nem renumera o anterior. */
public struct ConsentAcceptanceSyncView: Codable, JSONEncodable, Hashable {

    public enum ViewType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case consentAcceptance = "CONSENT_ACCEPTANCE"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let consentAcceptanceIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let consentTypeRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let documentVersionRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    public var viewType: ViewType
    /** Identidade do aceite; ausente em `ABSENT_DECLARED`, porque não há aceite a identificar. */
    public var consentAcceptanceId: String?
    public var consentType: String
    public var documentVersion: String
    public var state: ConsentAcceptanceState
    /** Instante do aceite; nulo em `ABSENT_DECLARED`. */
    public var acceptedAt: Date?

    public init(viewType: ViewType, consentAcceptanceId: String? = nil, consentType: String, documentVersion: String, state: ConsentAcceptanceState, acceptedAt: Date?) {
        self.viewType = viewType
        self.consentAcceptanceId = consentAcceptanceId
        self.consentType = consentType
        self.documentVersion = documentVersion
        self.state = state
        self.acceptedAt = acceptedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case viewType
        case consentAcceptanceId
        case consentType
        case documentVersion
        case state
        case acceptedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(viewType, forKey: .viewType)
        try container.encodeIfPresent(consentAcceptanceId, forKey: .consentAcceptanceId)
        try container.encode(consentType, forKey: .consentType)
        try container.encode(documentVersion, forKey: .documentVersion)
        try container.encode(state, forKey: .state)
        try container.encode(acceptedAt, forKey: .acceptedAt)
    }
}


extension ConsentAcceptanceSyncView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if viewType == .unknownDefaultOpenApi { return true }
        if state == .unknownDefaultOpenApi { return true }
        return false
    }
}
