//
// CreateInvitationJourneyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Entrada pública da URL canônica. &#x60;linkCode&#x60; é referência opaca e redigida, mas não é credencial de aceite. Nenhum dado pessoal é aceito neste corpo. */
public struct CreateInvitationJourneyRequest: Codable, JSONEncodable, Hashable {

    public static let linkCodeRule = StringRule(minLength: 22, maxLength: 128, pattern: "/^[A-Za-z0-9_-]+$/")
    public static let appInstallationIdRule = StringRule(minLength: 16, maxLength: 128, pattern: "/^[A-Za-z0-9._~-]+$/")
    public var linkCode: String
    public var platform: InvitationJourneyPlatform
    /** Identificador opaco opcional; nunca IDFA, AAID, e-mail ou fingerprint. */
    public var appInstallationId: String?

    public init(linkCode: String, platform: InvitationJourneyPlatform, appInstallationId: String? = nil) {
        self.linkCode = linkCode
        self.platform = platform
        self.appInstallationId = appInstallationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case linkCode
        case platform
        case appInstallationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(linkCode, forKey: .linkCode)
        try container.encode(platform, forKey: .platform)
        try container.encodeIfPresent(appInstallationId, forKey: .appInstallationId)
    }
}


extension CreateInvitationJourneyRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if platform == .unknownDefaultOpenApi { return true }
        return false
    }
}
