//
// CreatePrescriptionDraftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Cria um rascunho vazio ou derivado de uma versão publicada da mesma relação. A identidade nasce no cliente para que a criação offline e o retry convirjam para um único rascunho. */
public struct CreatePrescriptionDraftRequest: Codable, JSONEncodable, Hashable {

    public static let draftIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let studentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let nameRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let sourcePrescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identidade do rascunho, gerada pelo cliente; o servidor adota em vez de emitir outra. */
    public var draftId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var studentId: String
    /** Nome da prescrição, autorado pelo personal e preservado verbatim. */
    public var name: String
    /** Versão publicada de origem; derivar copia a estrutura para o rascunho novo sem tocar na origem. */
    public var sourcePrescriptionVersionId: String?

    public init(draftId: String, studentId: String, name: String, sourcePrescriptionVersionId: String? = nil) {
        self.draftId = draftId
        self.studentId = studentId
        self.name = name
        self.sourcePrescriptionVersionId = sourcePrescriptionVersionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case draftId
        case studentId
        case name
        case sourcePrescriptionVersionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(draftId, forKey: .draftId)
        try container.encode(studentId, forKey: .studentId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(sourcePrescriptionVersionId, forKey: .sourcePrescriptionVersionId)
    }
}
