//
// CreatePersonalExerciseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O exercício próprio inteiro, com a identidade que o cliente gerou. Nenhuma variante é enviada: o servidor a emite e a devolve. Os atributos opcionais são ausentes quando o personal não os informa — nunca lista vazia nem &#x60;null&#x60;. */
public struct CreatePersonalExerciseRequest: Codable, JSONEncodable, Hashable {

    public static let exerciseIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let nameRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let primaryMuscleRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let secondaryMusclesRule = ArrayRule(minItems: 1, maxItems: 20, uniqueItems: false)
    public static let equipmentRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let difficultyRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let mechanicRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let forceRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let stepsRule = ArrayRule(minItems: nil, maxItems: 12, uniqueItems: false)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseId: String
    /** Nome do exercício, como o personal o escreveu: texto autoral preservado, sem tradução nem reescrita, e que não segue `Accept-Language`. */
    public var name: String
    /** Texto de um atributo do exercício como a origem o entrega, no idioma que ela serve (`Content-Language`). Preservado como veio: o app não traduz, não reescreve e não o compara com rótulo de filtro — a relação com o filtro é o `similarQuery` do detalhe. */
    public var primaryMuscle: String
    /** Lista de textos de atributo. O servidor a entrega **sem repetição e na ordem da origem**, e o app a exibe nessa ordem (por isso o schema não declara `uniqueItems`: os clientes gerados a tratariam como conjunto, de ordem instável). Lista ausente significa que a origem não a informa; o contrato não usa lista vazia para isso. */
    public var secondaryMuscles: [String]?
    /** Texto de um atributo do exercício como a origem o entrega, no idioma que ela serve (`Content-Language`). Preservado como veio: o app não traduz, não reescreve e não o compara com rótulo de filtro — a relação com o filtro é o `similarQuery` do detalhe. */
    public var equipment: String?
    /** Texto de um atributo do exercício como a origem o entrega, no idioma que ela serve (`Content-Language`). Preservado como veio: o app não traduz, não reescreve e não o compara com rótulo de filtro — a relação com o filtro é o `similarQuery` do detalhe. */
    public var difficulty: String?
    /** Texto de um atributo do exercício como a origem o entrega, no idioma que ela serve (`Content-Language`). Preservado como veio: o app não traduz, não reescreve e não o compara com rótulo de filtro — a relação com o filtro é o `similarQuery` do detalhe. */
    public var mechanic: String?
    /** Texto de um atributo do exercício como a origem o entrega, no idioma que ela serve (`Content-Language`). Preservado como veio: o app não traduz, não reescreve e não o compara com rótulo de filtro — a relação com o filtro é o `similarQuery` do detalhe. */
    public var force: String?
    /** Passos de execução, em ordem, até 12 de 500 caracteres. O app os numera; o texto não traz numeração. Lista vazia é \"sem instruções escritas\". O schema não declara `uniqueItems`: a lista é ordenada e os clientes gerados a tratariam como conjunto, de ordem instável. */
    public var steps: [String]?

    public init(exerciseId: String, name: String, primaryMuscle: String, secondaryMuscles: [String]? = nil, equipment: String? = nil, difficulty: String? = nil, mechanic: String? = nil, force: String? = nil, steps: [String]? = nil) {
        self.exerciseId = exerciseId
        self.name = name
        self.primaryMuscle = primaryMuscle
        self.secondaryMuscles = secondaryMuscles
        self.equipment = equipment
        self.difficulty = difficulty
        self.mechanic = mechanic
        self.force = force
        self.steps = steps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exerciseId
        case name
        case primaryMuscle
        case secondaryMuscles
        case equipment
        case difficulty
        case mechanic
        case force
        case steps
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(exerciseId, forKey: .exerciseId)
        try container.encode(name, forKey: .name)
        try container.encode(primaryMuscle, forKey: .primaryMuscle)
        try container.encodeIfPresent(secondaryMuscles, forKey: .secondaryMuscles)
        try container.encodeIfPresent(equipment, forKey: .equipment)
        try container.encodeIfPresent(difficulty, forKey: .difficulty)
        try container.encodeIfPresent(mechanic, forKey: .mechanic)
        try container.encodeIfPresent(force, forKey: .force)
        try container.encodeIfPresent(steps, forKey: .steps)
    }
}
