//
// DeclineStudentInvitationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeclineStudentInvitationRequest: Codable, JSONEncodable, Hashable {

    public static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Credencial curta da jornada, recebida por HTTPS e nunca enviada em path, query, logs ou analytics. Ela não é o `linkCode` público. */
    public var token: String

    public init(token: String) {
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension DeclineStudentInvitationRequest: CustomStringConvertible {
    public var description: String { "DeclineStudentInvitationRequest([REDACTED])" }
}
