//
// DeferralSyncView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeferralSyncView: Codable, JSONEncodable, Hashable {

    public enum ViewType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case deferral = "DEFERRAL"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let deferralIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let executedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var viewType: ViewType
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var deferralId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    public var status: DeferralStatus
    public var prescribedPosition: Int
    public var executedPosition: Int

    public init(viewType: ViewType, deferralId: String, exerciseExecutionId: String, status: DeferralStatus, prescribedPosition: Int, executedPosition: Int) {
        self.viewType = viewType
        self.deferralId = deferralId
        self.exerciseExecutionId = exerciseExecutionId
        self.status = status
        self.prescribedPosition = prescribedPosition
        self.executedPosition = executedPosition
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case viewType
        case deferralId
        case exerciseExecutionId
        case status
        case prescribedPosition
        case executedPosition
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(viewType, forKey: .viewType)
        try container.encode(deferralId, forKey: .deferralId)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(status, forKey: .status)
        try container.encode(prescribedPosition, forKey: .prescribedPosition)
        try container.encode(executedPosition, forKey: .executedPosition)
    }
}


extension DeferralSyncView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if viewType == .unknownDefaultOpenApi { return true }
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
