//
// DeferralStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado do adiamento. &#x60;DEFERRED&#x60; é pendência aberta e bloqueia o encerramento da sessão enquanto não for resolvida; &#x60;RESUMED&#x60; e &#x60;SKIPPED&#x60; são terminais. O cliente lista as pendências abertas na tela de encerramento e o servidor recusa encerrar com pendência não declarada. */
public enum DeferralStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case deferred = "DEFERRED"
    case resumed = "RESUMED"
    case skipped = "SKIPPED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension DeferralStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
