//
// ExecutionRestRecordPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecutionRestRecordPayload: Codable, JSONEncodable, Hashable {

    public static let restPeriodIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let afterSetExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let targetSecondsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let adjustedTargetSecondsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let pausesRule = ArrayRule(minItems: nil, maxItems: 100, uniqueItems: false)
    public static let observationRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var restPeriodId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var afterSetExecutionId: String
    public var targetSeconds: Int
    public var adjustedTargetSeconds: Int?
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var startedAt: Date
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var endedAt: Date
    public var pauses: [RestPauseInterval]
    public var observation: String?

    public init(restPeriodId: String, exerciseExecutionId: String, afterSetExecutionId: String, targetSeconds: Int, adjustedTargetSeconds: Int? = nil, startedAt: Date, endedAt: Date, pauses: [RestPauseInterval], observation: String? = nil) {
        self.restPeriodId = restPeriodId
        self.exerciseExecutionId = exerciseExecutionId
        self.afterSetExecutionId = afterSetExecutionId
        self.targetSeconds = targetSeconds
        self.adjustedTargetSeconds = adjustedTargetSeconds
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.pauses = pauses
        self.observation = observation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restPeriodId
        case exerciseExecutionId
        case afterSetExecutionId
        case targetSeconds
        case adjustedTargetSeconds
        case startedAt
        case endedAt
        case pauses
        case observation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(restPeriodId, forKey: .restPeriodId)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(afterSetExecutionId, forKey: .afterSetExecutionId)
        try container.encode(targetSeconds, forKey: .targetSeconds)
        try container.encodeIfPresent(adjustedTargetSeconds, forKey: .adjustedTargetSeconds)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(endedAt, forKey: .endedAt)
        try container.encode(pauses, forKey: .pauses)
        try container.encodeIfPresent(observation, forKey: .observation)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension ExecutionRestRecordPayload: CustomStringConvertible {
    public var description: String { "ExecutionRestRecordPayload([REDACTED])" }
}
