//
// ExecutionSetRecordPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Fato imutável da série. &#x60;target&#x60; preserva o alvo apresentado; &#x60;actual&#x60; é o realizado e fica ausente somente em &#x60;SKIPPED&#x60;. Repetir a identidade com conteúdo diferente é conflito, nunca overwrite. */
public struct ExecutionSetRecordPayload: Codable, JSONEncodable, Hashable {

    public static let setExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedSetIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let setIndexRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let executedVariantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let equipmentInstanceIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let observationRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var setExecutionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var prescribedSetId: String
    public var setIndex: Int
    public var status: ExecutedSetStatus
    public var target: ExecutionTargetValues
    public var actual: WorkoutSetValues?
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var executedVariantId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var equipmentInstanceId: String?
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var startedAt: Date
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var completedAt: Date
    public var observation: String?

    public init(setExecutionId: String, exerciseExecutionId: String, prescribedSetId: String, setIndex: Int, status: ExecutedSetStatus, target: ExecutionTargetValues, actual: WorkoutSetValues? = nil, executedVariantId: String, equipmentInstanceId: String? = nil, startedAt: Date, completedAt: Date, observation: String? = nil) {
        self.setExecutionId = setExecutionId
        self.exerciseExecutionId = exerciseExecutionId
        self.prescribedSetId = prescribedSetId
        self.setIndex = setIndex
        self.status = status
        self.target = target
        self.actual = actual
        self.executedVariantId = executedVariantId
        self.equipmentInstanceId = equipmentInstanceId
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.observation = observation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case setExecutionId
        case exerciseExecutionId
        case prescribedSetId
        case setIndex
        case status
        case target
        case actual
        case executedVariantId
        case equipmentInstanceId
        case startedAt
        case completedAt
        case observation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(setExecutionId, forKey: .setExecutionId)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(prescribedSetId, forKey: .prescribedSetId)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encode(status, forKey: .status)
        try container.encode(target, forKey: .target)
        try container.encodeIfPresent(actual, forKey: .actual)
        try container.encode(executedVariantId, forKey: .executedVariantId)
        try container.encodeIfPresent(equipmentInstanceId, forKey: .equipmentInstanceId)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(observation, forKey: .observation)
    }
}


extension ExecutionSetRecordPayload: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension ExecutionSetRecordPayload: CustomStringConvertible {
    public var description: String { "ExecutionSetRecordPayload([REDACTED])" }
}
