//
// ExecutionSetObservationUpdatePayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecutionSetObservationUpdatePayload: Codable, JSONEncodable, Hashable {

    public static let setExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let observationRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var setExecutionId: String
    public var observation: String?
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var updatedAt: Date

    public init(setExecutionId: String, observation: String?, updatedAt: Date) {
        self.setExecutionId = setExecutionId
        self.observation = observation
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case setExecutionId
        case observation
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(setExecutionId, forKey: .setExecutionId)
        try container.encode(observation, forKey: .observation)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension ExecutionSetObservationUpdatePayload: CustomStringConvertible {
    public var description: String { "ExecutionSetObservationUpdatePayload([REDACTED])" }
}
