//
// ExecutionSessionStartPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Cria a sessão cuja identidade está em &#x60;aggregateId&#x60;. A atribuição e a versão publicada que autorizam o treino são preservadas como autoridades distintas; &#x60;workoutId&#x60; é derivado da atribuição, nunca enviado como substituto dela. */
public struct ExecutionSessionStartPayload: Codable, JSONEncodable, Hashable {

    public static let workoutAssignmentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var workoutAssignmentId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var prescriptionVersionId: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var startedAt: Date

    public init(workoutAssignmentId: String, prescriptionVersionId: String, startedAt: Date) {
        self.workoutAssignmentId = workoutAssignmentId
        self.prescriptionVersionId = prescriptionVersionId
        self.startedAt = startedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workoutAssignmentId
        case prescriptionVersionId
        case startedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workoutAssignmentId, forKey: .workoutAssignmentId)
        try container.encode(prescriptionVersionId, forKey: .prescriptionVersionId)
        try container.encode(startedAt, forKey: .startedAt)
    }
}
