//
// ExecutionExerciseReorderPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecutionExerciseReorderPayload: Codable, JSONEncodable, Hashable {

    public static let reorderIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let fromExecutedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let toExecutedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var reorderId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    public var prescribedPosition: Int
    public var fromExecutedPosition: Int
    public var toExecutedPosition: Int
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var reorderedAt: Date

    public init(reorderId: String, exerciseExecutionId: String, prescribedPosition: Int, fromExecutedPosition: Int, toExecutedPosition: Int, reorderedAt: Date) {
        self.reorderId = reorderId
        self.exerciseExecutionId = exerciseExecutionId
        self.prescribedPosition = prescribedPosition
        self.fromExecutedPosition = fromExecutedPosition
        self.toExecutedPosition = toExecutedPosition
        self.reorderedAt = reorderedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reorderId
        case exerciseExecutionId
        case prescribedPosition
        case fromExecutedPosition
        case toExecutedPosition
        case reorderedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reorderId, forKey: .reorderId)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(prescribedPosition, forKey: .prescribedPosition)
        try container.encode(fromExecutedPosition, forKey: .fromExecutedPosition)
        try container.encode(toExecutedPosition, forKey: .toExecutedPosition)
        try container.encode(reorderedAt, forKey: .reorderedAt)
    }
}
