//
// ExecutionExerciseResumePayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecutionExerciseResumePayload: Codable, JSONEncodable, Hashable {

    public static let deferralIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let executedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var deferralId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    public var executedPosition: Int
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var resumedAt: Date

    public init(deferralId: String, exerciseExecutionId: String, executedPosition: Int, resumedAt: Date) {
        self.deferralId = deferralId
        self.exerciseExecutionId = exerciseExecutionId
        self.executedPosition = executedPosition
        self.resumedAt = resumedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deferralId
        case exerciseExecutionId
        case executedPosition
        case resumedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deferralId, forKey: .deferralId)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(executedPosition, forKey: .executedPosition)
        try container.encode(resumedAt, forKey: .resumedAt)
    }
}
