//
// ExerciseCatalogFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Opções de cada filtro de busca. Cada &#x60;filter&#x60; aparece no máximo uma vez, e um &#x60;code&#x60; aparece no máximo uma vez dentro do seu filtro. */
public struct ExerciseCatalogFilters: Codable, JSONEncodable, Hashable {

    public var filters: [ExerciseCatalogFilterGroup]

    public init(filters: [ExerciseCatalogFilterGroup]) {
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filters, forKey: .filters)
    }
}
