//
// ExerciseReferencesView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Um resultado por &#x60;catalogRef&#x60; pedido, na ordem do pedido. */
public struct ExerciseReferencesView: Codable, JSONEncodable, Hashable {

    public static let itemsRule = ArrayRule(minItems: 1, maxItems: 60, uniqueItems: false)
    public var items: [ExerciseReferenceResolution]

    public init(items: [ExerciseReferenceResolution]) {
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
    }
}
