//
// ExerciseMediaAsset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Referência de mídia provider-agnostic. A identidade de cache é &#x60;(assetId, mediaVersion)&#x60;; &#x60;url&#x60; é uma referência de entrega renovável e nunca participa da identidade. OFFLINE_DOWNLOAD_ALLOWED exige sha256 e byteSize na emissão do backend; TEMPORARY_CACHE_ALLOWED só pode ser retido até offlineValidUntil. */
public struct ExerciseMediaAsset: Codable, JSONEncodable, Hashable {

    public enum Availability: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case available = "AVAILABLE"
        case unavailable = "UNAVAILABLE"
        case disabled = "DISABLED"
        case rightsExpired = "RIGHTS_EXPIRED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum MediaType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case image = "IMAGE"
        case video = "VIDEO"
        case animation = "ANIMATION"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum Usage: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case thumbnail = "THUMBNAIL"
        case demonstration = "DEMONSTRATION"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum OfflinePolicy: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case streamOnly = "STREAM_ONLY"
        case temporaryCacheAllowed = "TEMPORARY_CACHE_ALLOWED"
        case offlineDownloadAllowed = "OFFLINE_DOWNLOAD_ALLOWED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let assetIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let mediaVersionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let contentTypeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let durationSecondsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let sha256Rule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9a-f]{64}$/")
    public static let byteSizeRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var assetId: String
    /** Versão opaca do asset; comparar apenas por igualdade. */
    public var mediaVersion: String
    /** Estado explícito; nunca deve ser inferido da presença de URL. */
    public var availability: Availability
    public var mediaType: MediaType
    public var usage: Usage
    /** STREAM_ONLY proíbe persistência offline; TEMPORARY_CACHE_ALLOWED permite cache somente até offlineValidUntil; OFFLINE_DOWNLOAD_ALLOWED permite download verificável por sha256/byteSize dentro dos direitos vigentes. */
    public var offlinePolicy: OfflinePolicy
    /** Referência renovável de entrega; nula quando availability não é AVAILABLE. */
    public var url: String?
    public var contentType: String?
    public var durationSeconds: Int?
    public var sha256: String?
    public var byteSize: Int64?
    /** Expiração da URL de entrega, independente do direito offline. */
    public var expiresAt: Date?
    /** Limite de retenção offline; nulo para STREAM_ONLY. */
    public var offlineValidUntil: Date?

    public init(assetId: String, mediaVersion: String, availability: Availability, mediaType: MediaType, usage: Usage, offlinePolicy: OfflinePolicy, url: String?, contentType: String? = nil, durationSeconds: Int? = nil, sha256: String? = nil, byteSize: Int64? = nil, expiresAt: Date? = nil, offlineValidUntil: Date? = nil) {
        self.assetId = assetId
        self.mediaVersion = mediaVersion
        self.availability = availability
        self.mediaType = mediaType
        self.usage = usage
        self.offlinePolicy = offlinePolicy
        self.url = url
        self.contentType = contentType
        self.durationSeconds = durationSeconds
        self.sha256 = sha256
        self.byteSize = byteSize
        self.expiresAt = expiresAt
        self.offlineValidUntil = offlineValidUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetId
        case mediaVersion
        case availability
        case mediaType
        case usage
        case offlinePolicy
        case url
        case contentType
        case durationSeconds
        case sha256
        case byteSize
        case expiresAt
        case offlineValidUntil
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assetId, forKey: .assetId)
        try container.encode(mediaVersion, forKey: .mediaVersion)
        try container.encode(availability, forKey: .availability)
        try container.encode(mediaType, forKey: .mediaType)
        try container.encode(usage, forKey: .usage)
        try container.encode(offlinePolicy, forKey: .offlinePolicy)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encodeIfPresent(durationSeconds, forKey: .durationSeconds)
        try container.encodeIfPresent(sha256, forKey: .sha256)
        try container.encodeIfPresent(byteSize, forKey: .byteSize)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(offlineValidUntil, forKey: .offlineValidUntil)
    }
}


extension ExerciseMediaAsset: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if availability == .unknownDefaultOpenApi { return true }
        if mediaType == .unknownDefaultOpenApi { return true }
        if usage == .unknownDefaultOpenApi { return true }
        if offlinePolicy == .unknownDefaultOpenApi { return true }
        return false
    }
}
