//
// ExerciseHistoryEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExerciseHistoryEntry: Codable, JSONEncodable, Hashable {

    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var sessionId: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var performedAt: Date
    public var actual: WorkoutSetValues

    public init(sessionId: String, performedAt: Date, actual: WorkoutSetValues) {
        self.sessionId = sessionId
        self.performedAt = performedAt
        self.actual = actual
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case performedAt
        case actual
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(performedAt, forKey: .performedAt)
        try container.encode(actual, forKey: .actual)
    }
}
