//
// ExerciseExecutionSyncView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExerciseExecutionSyncView: Codable, JSONEncodable, Hashable {

    public enum ViewType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case exerciseExecution = "EXERCISE_EXECUTION"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum Status: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case pending = "PENDING"
        case inProgress = "IN_PROGRESS"
        case deferred = "DEFERRED"
        case completed = "COMPLETED"
        case skipped = "SKIPPED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedExerciseIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let executedVariantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let equipmentInstanceIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let executedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var viewType: ViewType
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var sessionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var prescribedExerciseId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var executedVariantId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var equipmentInstanceId: String?
    public var prescribedPosition: Int
    public var executedPosition: Int
    public var status: Status

    public init(viewType: ViewType, exerciseExecutionId: String, sessionId: String, prescribedExerciseId: String, executedVariantId: String, equipmentInstanceId: String? = nil, prescribedPosition: Int, executedPosition: Int, status: Status) {
        self.viewType = viewType
        self.exerciseExecutionId = exerciseExecutionId
        self.sessionId = sessionId
        self.prescribedExerciseId = prescribedExerciseId
        self.executedVariantId = executedVariantId
        self.equipmentInstanceId = equipmentInstanceId
        self.prescribedPosition = prescribedPosition
        self.executedPosition = executedPosition
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case viewType
        case exerciseExecutionId
        case sessionId
        case prescribedExerciseId
        case executedVariantId
        case equipmentInstanceId
        case prescribedPosition
        case executedPosition
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(viewType, forKey: .viewType)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(prescribedExerciseId, forKey: .prescribedExerciseId)
        try container.encode(executedVariantId, forKey: .executedVariantId)
        try container.encodeIfPresent(equipmentInstanceId, forKey: .equipmentInstanceId)
        try container.encode(prescribedPosition, forKey: .prescribedPosition)
        try container.encode(executedPosition, forKey: .executedPosition)
        try container.encode(status, forKey: .status)
    }
}


extension ExerciseExecutionSyncView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if viewType == .unknownDefaultOpenApi { return true }
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
