//
// HealthView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthView: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case up = "UP"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Confirma exclusivamente que o processo está vivo. */
    public var status: Status

    public init(status: Status) {
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
    }
}


extension HealthView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
