//
// IdentityEmailKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Que tipo de e-mail a conta autenticada tem, para que a interface saiba se pode mostrá-lo. &#x60;EMAIL&#x60; é um endereço comum, exibível. &#x60;HIDDEN_EMAIL&#x60; é o relay da Apple (*Ocultar Meu E-mail*), que não é o e-mail pessoal da pessoa e nunca é exibido nem publicado (ADR-0007 §5): toda projeção que usa este vocabulário omite o endereço quando o valor é &#x60;HIDDEN_EMAIL&#x60;. É o mesmo vocabulário em &#x60;AuthenticatedIdentityProfile.emailKind&#x60; e em &#x60;StudentInvitationAcceptanceContextView.authenticatedIdentity.kind&#x60;. */
public enum IdentityEmailKind: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case email = "EMAIL"
    case hiddenEmail = "HIDDEN_EMAIL"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension IdentityEmailKind: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
