//
// IdentityJourneyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Resposta correlacionada que vincula próxima etapa, convite e sessão. A escolha de jornada preserva o convite e exige ação posterior; autenticação e correspondência de e-mail nunca autorizam vínculo. **A escolha de jornada não é campo de conta.** Não existe papel único ou global previamente salvo: o servidor resolve o contexto de entrada a cada entrada e, havendo convite válido, &#x60;ENTRY_JOURNEY_CHOICE_REQUIRED&#x60; pede a escolha sem pré-selecionar nenhuma jornada e sem inferi-la do provedor de identidade usado. **Seguir pela jornada profissional não consome nem cancela o convite**: por isso &#x60;ONBOARDING_REQUIRED&#x60; admite contexto preservado, e não apenas ausente. Falha de rede ou resposta inconclusiva é estado indeterminado **do cliente** e **nunca** pode ser lida como ausência de convite; ela não é emitida aqui, porque uma resposta desta operação é, por definição, conclusiva. */
public struct IdentityJourneyResponse: Codable, JSONEncodable, Hashable {

    public enum NextStep: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case otpRequired = "OTP_REQUIRED"
        case onboardingRequired = "ONBOARDING_REQUIRED"
        case sessionIssued = "SESSION_ISSUED"
        case entryJourneyChoiceRequired = "ENTRY_JOURNEY_CHOICE_REQUIRED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum InvitationContext: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case absent = "ABSENT"
        case preserved = "PRESERVED"
        case multiplePreserved = "MULTIPLE_PRESERVED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let continuationRule = StringRule(minLength: 32, maxLength: nil, pattern: nil)
    public var continuation: String
    /** Próxima etapa decidida pelo servidor. `ENTRY_JOURNEY_CHOICE_REQUIRED` publica o momento em que a pessoa escolhe, com o mesmo peso, entre a jornada de aluno daquele convite e a jornada profissional; a escolha não é persistida como papel e a entrada seguinte com convite válido volta a perguntar. **Não existe passo de confirmação de convite nem de divergência de e-mail.** Sob `DEC-CONV-2`, a conta cujo e-mail diverge do destino do convite resolve a divergência por prova de posse do endereço convidado, que o contexto de aceite publica em `emailOwnership.status = PROOF_REQUIRED`; nunca por uma tela de \"confirmar que sou eu\" depois do login. */
    public var nextStep: NextStep
    /** Ausência, preservação de um convite ou preservação de mais de um. Preservado significa que o convite permanece utilizável e não foi consumido por esta etapa; multiplicidade não elege convite nem cria relação. */
    public var invitationContext: InvitationContext
    public var session: SessionResponse?

    public init(continuation: String, nextStep: NextStep, invitationContext: InvitationContext, session: SessionResponse? = nil) {
        self.continuation = continuation
        self.nextStep = nextStep
        self.invitationContext = invitationContext
        self.session = session
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case continuation
        case nextStep
        case invitationContext
        case session
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(continuation, forKey: .continuation)
        try container.encode(nextStep, forKey: .nextStep)
        try container.encode(invitationContext, forKey: .invitationContext)
        try container.encodeIfPresent(session, forKey: .session)
    }
}


extension IdentityJourneyResponse: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if nextStep == .unknownDefaultOpenApi { return true }
        if invitationContext == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension IdentityJourneyResponse: CustomStringConvertible {
    public var description: String { "IdentityJourneyResponse([REDACTED])" }
}
