//
// InvitationEmailDiscoveryVerificationView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Resultado da posse provada: os convites pendentes do endereço e a prova de endereço. Não carrega token de aceite, &#x60;linkCode&#x60; nem &#x60;journeyToken&#x60;, e não é prova de posse de convite: essa nasce só na jornada do convite escolhido. */
public struct InvitationEmailDiscoveryVerificationView: Codable, JSONEncodable, Hashable {

    public static let discoveryProofIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let itemsRule = ArrayRule(minItems: nil, maxItems: 20, uniqueItems: false)
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var verifiedAt: Date
    /** Prova de endereço: de uso único, presa à conta e válida por 30 minutos. Não autoriza aceite; o cliente a ecoa em `emailDiscoveryProofId` ao criar a jornada de um dos `items`. */
    public var discoveryProofId: String
    /** Fim da validade da prova de endereço, servido pelo servidor. */
    public var discoveryProofExpiresAt: Date
    /** Convites pendentes do endereço provado, na mesma projeção mínima de `GET /student-invitations/pending`. Lista vazia é resposta válida. */
    public var items: [StudentInvitationView]

    public init(verifiedAt: Date, discoveryProofId: String, discoveryProofExpiresAt: Date, items: [StudentInvitationView]) {
        self.verifiedAt = verifiedAt
        self.discoveryProofId = discoveryProofId
        self.discoveryProofExpiresAt = discoveryProofExpiresAt
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verifiedAt
        case discoveryProofId
        case discoveryProofExpiresAt
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verifiedAt, forKey: .verifiedAt)
        try container.encode(discoveryProofId, forKey: .discoveryProofId)
        try container.encode(discoveryProofExpiresAt, forKey: .discoveryProofExpiresAt)
        try container.encode(items, forKey: .items)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension InvitationEmailDiscoveryVerificationView: CustomStringConvertible {
    public var description: String { "InvitationEmailDiscoveryVerificationView([REDACTED])" }
}
