//
// InvitationEmailOwnershipChallengeView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Desafio emitido para o endereço convidado, com os parâmetros que o servidor decide. A projeção **não publica o código**, **não publica o endereço em claro** e **não publica quantas tentativas restam**. */
public struct InvitationEmailOwnershipChallengeView: Codable, JSONEncodable, Hashable {

    public static let challengeIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let invitationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let inviteeEmailMaskedRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let maxAttemptsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var challengeId: String
    /** Convite a que este desafio está preso. A prova dele não vale para nenhum outro. */
    public var invitationId: String
    /** Destino irrecuperavelmente mascarado, para reconhecimento visual. */
    public var inviteeEmailMasked: String
    /** Fim da validade, servido pelo servidor. O cliente exibe o que recebeu e não conta o tempo por conta própria. */
    public var expiresAt: Date
    /** Instante a partir do qual pedir outro código deixa de ser recusado. Servido pelo servidor; nunca um cronômetro local. */
    public var resendAvailableAt: Date
    /** Limite de tentativas do desafio, servido para que nenhum app o embuta. O saldo restante **não** é publicado. */
    public var maxAttempts: Int

    public init(challengeId: String, invitationId: String, inviteeEmailMasked: String, expiresAt: Date, resendAvailableAt: Date, maxAttempts: Int) {
        self.challengeId = challengeId
        self.invitationId = invitationId
        self.inviteeEmailMasked = inviteeEmailMasked
        self.expiresAt = expiresAt
        self.resendAvailableAt = resendAvailableAt
        self.maxAttempts = maxAttempts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challengeId
        case invitationId
        case inviteeEmailMasked
        case expiresAt
        case resendAvailableAt
        case maxAttempts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challengeId, forKey: .challengeId)
        try container.encode(invitationId, forKey: .invitationId)
        try container.encode(inviteeEmailMasked, forKey: .inviteeEmailMasked)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(resendAvailableAt, forKey: .resendAvailableAt)
        try container.encode(maxAttempts, forKey: .maxAttempts)
    }
}
