//
// InvitationEmailOwnershipProofView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Prova de posse do endereço convidado, **escopada a um único convite**. Ela não adiciona e não troca o e-mail da conta, não cria identidade e não vale para um segundo convite. */
public struct InvitationEmailOwnershipProofView: Codable, JSONEncodable, Hashable {

    public static let proofIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let invitationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Valor que o aceite daquele convite ecoa em `emailOwnershipProofId`. */
    public var proofId: String
    /** Único convite que esta prova autoriza. */
    public var invitationId: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var verifiedAt: Date

    public init(proofId: String, invitationId: String, verifiedAt: Date) {
        self.proofId = proofId
        self.invitationId = invitationId
        self.verifiedAt = verifiedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proofId
        case invitationId
        case verifiedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(proofId, forKey: .proofId)
        try container.encode(invitationId, forKey: .invitationId)
        try container.encode(verifiedAt, forKey: .verifiedAt)
    }
}
