//
// InvitationJourneyView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Credencial curta que envolve o convite sem publicar o token de aceite. O &#x60;journeyToken&#x60; é usado no campo &#x60;token&#x60; das operações maduras de resolução, contexto, prova de e-mail, recusa e aceite; o servidor resolve internamente o convite e preserva uma única porta de aceite. */
public struct InvitationJourneyView: Codable, JSONEncodable, Hashable {

    public static let journeyIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let journeyTokenRule = StringRule(minLength: 32, maxLength: 256, pattern: nil)
    /** Identidade pública opaca da jornada; não autoriza operação isoladamente. */
    public var journeyId: String
    /** Segredo curto, retornado uma vez, protegido em storage seguro e nunca colocado em URL. */
    public var journeyToken: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var expiresAt: Date
    public var invitation: StudentInvitationView
    public var nextAction: InvitationJourneyNextAction

    public init(journeyId: String, journeyToken: String, expiresAt: Date, invitation: StudentInvitationView, nextAction: InvitationJourneyNextAction) {
        self.journeyId = journeyId
        self.journeyToken = journeyToken
        self.expiresAt = expiresAt
        self.invitation = invitation
        self.nextAction = nextAction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case journeyId
        case journeyToken
        case expiresAt
        case invitation
        case nextAction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(journeyId, forKey: .journeyId)
        try container.encode(journeyToken, forKey: .journeyToken)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(invitation, forKey: .invitation)
        try container.encode(nextAction, forKey: .nextAction)
    }
}


extension InvitationJourneyView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if nextAction == .unknownDefaultOpenApi { return true }
        return false
    }
}
