//
// Locale.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Locale efetivo aprovado para o MVP; pt-BR é padrão e fallback. */
public enum Locale: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case ptBr = "pt-BR"
    case enUs = "en-US"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension Locale: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
