//
// PendingStudentInvitationPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Convites ainda utilizáveis ligados aos e-mails verificados da sessão. Lista vazia é resposta legítima e não confirma a existência de convite para outro destino. */
public struct PendingStudentInvitationPage: Codable, JSONEncodable, Hashable {

    public static let itemsRule = ArrayRule(minItems: nil, maxItems: 20, uniqueItems: false)
    public var items: [StudentInvitationView]

    public init(items: [StudentInvitationView]) {
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
    }
}
