//
// PersonalStudentInvitationListItemView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Projeção de um convite dentro da coleção do personal. Espelha &#x60;PersonalStudentInvitationView&#x60;, porém SEM &#x60;shareableUrl&#x60; e sem qualquer token: o bearer secret de aceite é devolvido uma única vez na criação e é estruturalmente impossível nesta coleção. &#x60;additionalProperties: false&#x60; impede a reintrodução do segredo por qualquer campo extra. */
public struct PersonalStudentInvitationListItemView: Codable, JSONEncodable, Hashable {

    public static let invitationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let studentDisplayNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let destinationMaskedRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let availableActionsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var invitationId: String
    /** Metadado privado do personal; nulo quando não informado e nunca exposto em resolução pública. */
    public var studentDisplayName: String?
    public var status: StudentInvitationLifecycleStatus
    public var deliveryStatus: StudentInvitationDeliveryStatus
    /** E-mail convidado, irreversivelmente mascarado. Todo convite emitido a partir da emissão v2 é `email-bound` e tem destino, de modo que o campo está presente em todos eles. Ele permanece ESTRUTURALMENTE OPCIONAL por uma razão medida e não por indecisão: convites emitidos antes desta versão, sob a modalidade de link, não têm destino nenhum, o servidor omite a chave, e um cliente que a exigisse falharia a decodificação antes de o aluno ver o convite — foi o que aconteceu em 0.26.0 e o que 0.27.0 corrigiu. Ausência é estrutural, nunca `null` e nunca string vazia. O destino em claro nunca é devolvido. */
    public var destinationMasked: String?
    /** Tentativas de entrega observadas, da mais recente para a mais antiga. Estruturalmente ausente enquanto nenhuma foi registrada, nunca `null`, e nenhuma delas afirma recebimento ou leitura pelo aluno. */
    public var deliveryAttempts: [StudentInvitationDeliveryAttemptView]?
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var sentAt: Date
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var expiresAt: Date
    /** Instante RFC 3339 da aceitação; nulo enquanto o convite não foi aceito. */
    public var acceptedAt: Date?
    /** Identificador público opaco da relação, que nasce somente após autenticação e aceitação válidas; nulo até lá. */
    public var relationshipId: String?
    public var availableActions: Set<PersonalStudentInvitationAction>

    public init(invitationId: String, studentDisplayName: String?, status: StudentInvitationLifecycleStatus, deliveryStatus: StudentInvitationDeliveryStatus, destinationMasked: String? = nil, deliveryAttempts: [StudentInvitationDeliveryAttemptView]? = nil, sentAt: Date, expiresAt: Date, acceptedAt: Date?, relationshipId: String?, availableActions: Set<PersonalStudentInvitationAction>) {
        self.invitationId = invitationId
        self.studentDisplayName = studentDisplayName
        self.status = status
        self.deliveryStatus = deliveryStatus
        self.destinationMasked = destinationMasked
        self.deliveryAttempts = deliveryAttempts
        self.sentAt = sentAt
        self.expiresAt = expiresAt
        self.acceptedAt = acceptedAt
        self.relationshipId = relationshipId
        self.availableActions = availableActions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invitationId
        case studentDisplayName
        case status
        case deliveryStatus
        case destinationMasked
        case deliveryAttempts
        case sentAt
        case expiresAt
        case acceptedAt
        case relationshipId
        case availableActions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invitationId, forKey: .invitationId)
        try container.encode(studentDisplayName, forKey: .studentDisplayName)
        try container.encode(status, forKey: .status)
        try container.encode(deliveryStatus, forKey: .deliveryStatus)
        try container.encodeIfPresent(destinationMasked, forKey: .destinationMasked)
        try container.encodeIfPresent(deliveryAttempts, forKey: .deliveryAttempts)
        try container.encode(sentAt, forKey: .sentAt)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(acceptedAt, forKey: .acceptedAt)
        try container.encode(relationshipId, forKey: .relationshipId)
        try container.encode(availableActions, forKey: .availableActions)
    }
}


extension PersonalStudentInvitationListItemView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        if deliveryStatus == .unknownDefaultOpenApi { return true }
        return false
    }
}
