//
// PersonalAttentionWindow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Janela e limiar que sustentam um item de **projeção**, calculados no servidor. Ela existe para que o item se explique: quantas ocorrências foram observadas, a partir de quantas o motivo passa a ser emitido e qual o tamanho da janela. Não é estatística publicada — não há média, mediana, carga representativa nem volume agregado —, e o cliente não recalcula limiar, não compara janelas entre alunos e não converte contagem em gravidade. */
public struct PersonalAttentionWindow: Codable, JSONEncodable, Hashable {

    public static let observedCountRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let thresholdRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let sizeRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Ocorrências observadas dentro da janela que sustentam o limiar. */
    public var observedCount: Int
    /** A partir de quantas ocorrências o motivo passa a ser emitido. */
    public var threshold: Int
    /** Tamanho da janela, na unidade declarada em `unit`. */
    public var size: Int
    public var unit: PersonalAttentionWindowUnit

    public init(observedCount: Int, threshold: Int, size: Int, unit: PersonalAttentionWindowUnit) {
        self.observedCount = observedCount
        self.threshold = threshold
        self.size = size
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case observedCount
        case threshold
        case size
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(observedCount, forKey: .observedCount)
        try container.encode(threshold, forKey: .threshold)
        try container.encode(size, forKey: .size)
        try container.encode(unit, forKey: .unit)
    }
}


extension PersonalAttentionWindow: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if unit == .unknownDefaultOpenApi { return true }
        return false
    }
}
