//
// PersonalStudentExerciseSubstitutionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Substituição registrada, com o **motivo estruturado** do enum já canônico. Trocar de variante, trocar o equipamento e usar um exercício alternativo são **três eventos diferentes**, e o registro preserva qual ocorreu, sem inferência. Esta projeção não publica o catálogo de opções de substituição nem a alternativa descartada: a lista de opções continua sem superfície. */
public struct PersonalStudentExerciseSubstitutionView: Codable, JSONEncodable, Hashable {

    public var type: SubstitutionType
    public var reason: SubstitutionReason
    public var authorizationSource: SubstitutionAuthorizationSource
    public var scope: SubstitutionScope

    public init(type: SubstitutionType, reason: SubstitutionReason, authorizationSource: SubstitutionAuthorizationSource, scope: SubstitutionScope) {
        self.type = type
        self.reason = reason
        self.authorizationSource = authorizationSource
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case reason
        case authorizationSource
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(reason, forKey: .reason)
        try container.encode(authorizationSource, forKey: .authorizationSource)
        try container.encode(scope, forKey: .scope)
    }
}


extension PersonalStudentExerciseSubstitutionView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if reason == .unknownDefaultOpenApi { return true }
        if authorizationSource == .unknownDefaultOpenApi { return true }
        if scope == .unknownDefaultOpenApi { return true }
        return false
    }
}
