//
// PersonalStudentOperationsPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** As combinações que o servidor nunca emite, declaradas como proibição e não como &#x60;if&#x60;/&#x60;then&#x60;: uma página selada como &#x60;FACT&#x60;, porque esta leitura é integralmente derivada, e uma página &#x60;PROJECTION&#x60; sem o corte &#x60;asOf&#x60; que o selo exige. A forma é a que o gate de compatibilidade percorre — ele recursa em &#x60;allOf&#x60;, &#x60;anyOf&#x60; e &#x60;not&#x60; e nunca em &#x60;if&#x60;/&#x60;then&#x60;/&#x60;else&#x60; — e mantém os exemplos publicados verificáveis contra o schema, como em &#x60;EntryContextView&#x60;. */
public struct PersonalStudentOperationsPage: Codable, JSONEncodable, Hashable {

    public static let nextCursorRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Instante do servidor em que esta página foi calculada, obrigatório em toda leitura. Ele amarra cada estado a um corte, e é o que impede que uma leitura de três dias atrás e uma de três segundos atrás sejam indistinguíveis. */
    public var asOf: Date
    /** Selo de origem já publicado, reusado sem variação. Nesta leitura ele é sempre `PROJECTION`, porque nada aqui é entidade armazenada: cada item é derivado dos fatos de relacionamento, anamnese, elegibilidade, atribuição e execução, e o selo `PROJECTION` é o que torna `asOf` exigível por schema, e não só por prosa. */
    public var origin: SyncItemOrigin
    /** Vínculos ativos desta página, na ordenação total definida pela operação. Lista vazia é exatamente zero vínculos ativos nesta leitura, e nunca erro, indisponibilidade ou afirmação sobre o estado de alguém. */
    public var items: [PersonalStudentOperationItemView]
    /** Cursor opaco da próxima página, **nulo na última**. Nunca é offset, índice ou dado a ser interpretado pelo cliente. */
    public var nextCursor: String?

    public init(asOf: Date, origin: SyncItemOrigin, items: [PersonalStudentOperationItemView], nextCursor: String?) {
        self.asOf = asOf
        self.origin = origin
        self.items = items
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asOf
        case origin
        case items
        case nextCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(asOf, forKey: .asOf)
        try container.encode(origin, forKey: .origin)
        try container.encode(items, forKey: .items)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}


extension PersonalStudentOperationsPage: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if origin == .unknownDefaultOpenApi { return true }
        return false
    }
}
