//
// PersonalFirstDayOfWeekSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Procedência do &#x60;firstDayOfWeek&#x60; em vigor, publicada porque o valor sozinho não a carrega: &#x60;MONDAY&#x60; declarado pela pessoa e &#x60;MONDAY&#x60; deduzido do locale são o mesmo byte e decisões opostas de produto. &#x60;DECLARED_BY_PERSONAL&#x60; é a escolha explícita da pessoa, que o cliente pode pré-preencher e deve devolver ao salvar sob pena de apagá-la; &#x60;DERIVED_FROM_LOCALE&#x60; é a dedução do servidor, que não é resposta da pessoa e não deve ser apresentada como se fosse. A procedência é observada, nunca enviada: nenhum request a transporta, e por isso ela não pode ser forjada pelo cliente. */
public enum PersonalFirstDayOfWeekSource: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case declaredByPersonal = "DECLARED_BY_PERSONAL"
    case derivedFromLocale = "DERIVED_FROM_LOCALE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PersonalFirstDayOfWeekSource: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
