//
// PersonalExerciseVideoVariantView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Derivado temporário de leitura. A URL é uma capacidade efêmera de leitura, de curta duração e sempre acompanhada de &#x60;expiresAt&#x60;, e **nunca** é identidade: identidade é &#x60;assetId&#x60; + &#x60;mediaVersion&#x60;. O cliente não persiste, não indexa, não compartilha nem registra em log esta URL, não deriva outra a partir dela e não a reutiliza depois da reprodução. Depois de um tombstone nenhuma URL nova é emitida, mas uma já emitida pode servir até o seu &#x60;expiresAt&#x60;. */
public struct PersonalExerciseVideoVariantView: Codable, JSONEncodable, Hashable {

    public static let contentTypeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let urlRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var kind: PersonalExerciseVideoVariantKind
    /** Tipo de mídia do derivado, para o player escolher o decodificador. */
    public var contentType: String
    /** URL temporária de leitura, opaca e de curta duração. Não é identidade, não é estável entre leituras e não deve ser armazenada. */
    public var url: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var expiresAt: Date

    public init(kind: PersonalExerciseVideoVariantKind, contentType: String, url: String, expiresAt: Date) {
        self.kind = kind
        self.contentType = contentType
        self.url = url
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case contentType
        case url
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(url, forKey: .url)
        try container.encode(expiresAt, forKey: .expiresAt)
    }
}


extension PersonalExerciseVideoVariantView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if kind == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension PersonalExerciseVideoVariantView: CustomStringConvertible {
    public var description: String { "PersonalExerciseVideoVariantView([REDACTED])" }
}
