//
// PersonalMeasurementSystem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PersonalMeasurementSystem: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case metric = "METRIC"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PersonalMeasurementSystem: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
