//
// PersonalStudentOperationAnamnesisView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** As combinações proibidas do estado da anamnese, na forma que o gate de compatibilidade percorre: concluída sem a versão que a sustenta, e versão publicada com estado que não a comporta. */
public struct PersonalStudentOperationAnamnesisView: Codable, JSONEncodable, Hashable {

    public var state: StudentAnamnesisState
    /** Referência à versão concluída mais recente — identidade, número e data —, sem o seu conteúdo, reusando a referência já publicada. Presente exatamente quando `state` é `COMPLETED`, e ausente nos outros dois estados; a ausência é ausência, nunca versão zero. */
    public var latestCompletedVersion: StudentAnamnesisVersionRef?

    public init(state: StudentAnamnesisState, latestCompletedVersion: StudentAnamnesisVersionRef? = nil) {
        self.state = state
        self.latestCompletedVersion = latestCompletedVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case state
        case latestCompletedVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(latestCompletedVersion, forKey: .latestCompletedVersion)
    }
}


extension PersonalStudentOperationAnamnesisView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if state == .unknownDefaultOpenApi { return true }
        return false
    }
}
