//
// PersonalExerciseVideoUploadHeader.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Cabeçalho obrigatório do PUT temporário, opaco para o cliente: ele repassa o par exatamente como recebido e não interpreta, reordena nem completa a lista. */
public struct PersonalExerciseVideoUploadHeader: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let valueRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Nome do cabeçalho a repassar no PUT. */
    public var name: String
    /** Valor a repassar sem alteração. É material efêmero de uma única tentativa de envio e não deve ser registrado em log nem persistido. */
    public var value: String

    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension PersonalExerciseVideoUploadHeader: CustomStringConvertible {
    public var description: String { "PersonalExerciseVideoUploadHeader([REDACTED])" }
}
