//
// PersonalStudentAnamnesisVersionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Conteúdo de **uma** versão autorizada ao personal deste vínculo, relida e reautorizada a cada leitura pelo mesmo predicado de &#x60;getPersonalStudentAnamnesis&#x60;. O identificador opaco não concede acesso. */
public struct PersonalStudentAnamnesisVersionView: Codable, JSONEncodable, Hashable {

    public static let studentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var studentId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var relationshipId: String
    public var access: PersonalAnamnesisVersionAccess
    public var version: StudentAnamnesisVersionView

    public init(studentId: String, relationshipId: String, access: PersonalAnamnesisVersionAccess, version: StudentAnamnesisVersionView) {
        self.studentId = studentId
        self.relationshipId = relationshipId
        self.access = access
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case studentId
        case relationshipId
        case access
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(studentId, forKey: .studentId)
        try container.encode(relationshipId, forKey: .relationshipId)
        try container.encode(access, forKey: .access)
        try container.encode(version, forKey: .version)
    }
}


extension PersonalStudentAnamnesisVersionView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if access == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension PersonalStudentAnamnesisVersionView: CustomStringConvertible {
    public var description: String { "PersonalStudentAnamnesisVersionView([REDACTED])" }
}
