//
// PersonalExerciseVideoValidationProblemDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** As combinações que o servidor nunca emite, declaradas como proibição e não como &#x60;if&#x60;/&#x60;then&#x60;: &#x60;maxDurationSeconds&#x60; fora de &#x60;EXERCISE_VIDEO_TOO_LONG&#x60; — e &#x60;EXERCISE_VIDEO_TOO_LONG&#x60; sem ele —, e a divergência de checksum ou de tamanho sem o &#x60;fieldErrors&#x60; que aponta o campo. */
public struct PersonalExerciseVideoValidationProblemDetails: Codable, JSONEncodable, Hashable {

    public enum Status: Int, Codable, CaseIterable, CaseIterableDefaultsLast {
        case _422 = 422
        case unknownDefaultOpenApi = 11184809
    }
    public enum Code: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case validationFailed = "VALIDATION_FAILED"
        case exerciseVideoRightsNotDeclared = "EXERCISE_VIDEO_RIGHTS_NOT_DECLARED"
        case exerciseVideoTooLong = "EXERCISE_VIDEO_TOO_LONG"
        case exerciseVideoUploadMismatch = "EXERCISE_VIDEO_UPLOAD_MISMATCH"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let correlationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let fieldErrorsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public static let maxDurationSecondsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** URI estável que identifica a classe do problema. */
    public var type: String
    /** Resumo legível e estável para a classe do problema. server_localized; `code` é a autoridade estável para lógica de cliente, `title` nunca deve ser usado como chave de decisão. */
    public var title: String
    public var status: Status
    public var code: Code
    /** Explicação contextual segura para exibição ou diagnóstico. */
    public var detail: String?
    /** Referência opcional à ocorrência específica do problema. */
    public var instance: String?
    /** Identificador opaco de correlação, repetido em Problem Details quando houver erro. */
    public var correlationId: String
    public var fieldErrors: [FieldError]?
    public var maxDurationSeconds: Int?

    public init(type: String, title: String, status: Status, code: Code, detail: String? = nil, instance: String? = nil, correlationId: String, fieldErrors: [FieldError]? = nil, maxDurationSeconds: Int? = nil) {
        self.type = type
        self.title = title
        self.status = status
        self.code = code
        self.detail = detail
        self.instance = instance
        self.correlationId = correlationId
        self.fieldErrors = fieldErrors
        self.maxDurationSeconds = maxDurationSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case title
        case status
        case code
        case detail
        case instance
        case correlationId
        case fieldErrors
        case maxDurationSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(title, forKey: .title)
        try container.encode(status, forKey: .status)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(instance, forKey: .instance)
        try container.encode(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(fieldErrors, forKey: .fieldErrors)
        try container.encodeIfPresent(maxDurationSeconds, forKey: .maxDurationSeconds)
    }
}


extension PersonalExerciseVideoValidationProblemDetails: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        if code == .unknownDefaultOpenApi { return true }
        return false
    }
}
