//
// PersonalRecentExerciseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Exercício que o personal já prescreveu numa versão publicada. &#x60;label&#x60; é o texto que ele usou na prescrição, e **não** o nome da origem: este item não consulta a origem. &#x60;exerciseId&#x60; e &#x60;variantId&#x60; são os da prescrição, e por isso sempre estão presentes. Atributos só vêm quando o Pliora os tem. */
public struct PersonalRecentExerciseItem: Codable, JSONEncodable, Hashable {

    public static let exerciseIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let variantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let labelRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let primaryMusclesRule = ArrayRule(minItems: 1, maxItems: 20, uniqueItems: false)
    public static let equipmentRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var variantId: String
    public var origin: ExerciseOrigin
    public var label: String
    /** Se o exercício é favorito do personal autenticado. */
    public var favorite: Bool
    /** Instante da publicação mais recente do personal que usou este exercício. */
    public var lastPrescribedAt: Date
    /** Lista de textos de atributo. O servidor a entrega **sem repetição e na ordem da origem**, e o app a exibe nessa ordem (por isso o schema não declara `uniqueItems`: os clientes gerados a tratariam como conjunto, de ordem instável). Lista ausente significa que a origem não a informa; o contrato não usa lista vazia para isso. */
    public var primaryMuscles: [String]?
    /** Texto de um atributo do exercício como a origem o entrega, no idioma que ela serve (`Content-Language`). Preservado como veio: o app não traduz, não reescreve e não o compara com rótulo de filtro — a relação com o filtro é o `similarQuery` do detalhe. */
    public var equipment: String?

    public init(exerciseId: String, variantId: String, origin: ExerciseOrigin, label: String, favorite: Bool, lastPrescribedAt: Date, primaryMuscles: [String]? = nil, equipment: String? = nil) {
        self.exerciseId = exerciseId
        self.variantId = variantId
        self.origin = origin
        self.label = label
        self.favorite = favorite
        self.lastPrescribedAt = lastPrescribedAt
        self.primaryMuscles = primaryMuscles
        self.equipment = equipment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exerciseId
        case variantId
        case origin
        case label
        case favorite
        case lastPrescribedAt
        case primaryMuscles
        case equipment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(exerciseId, forKey: .exerciseId)
        try container.encode(variantId, forKey: .variantId)
        try container.encode(origin, forKey: .origin)
        try container.encode(label, forKey: .label)
        try container.encode(favorite, forKey: .favorite)
        try container.encode(lastPrescribedAt, forKey: .lastPrescribedAt)
        try container.encodeIfPresent(primaryMuscles, forKey: .primaryMuscles)
        try container.encodeIfPresent(equipment, forKey: .equipment)
    }
}


extension PersonalRecentExerciseItem: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if origin == .unknownDefaultOpenApi { return true }
        return false
    }
}
