//
// PersonalSpecialty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Declaração de atuação; nunca é capability ou autorização. */
public enum PersonalSpecialty: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case hypertrophy = "HYPERTROPHY"
    case weightLoss = "WEIGHT_LOSS"
    case sportsPerformance = "SPORTS_PERFORMANCE"
    case rehabilitation = "REHABILITATION"
    case healthWellness = "HEALTH_WELLNESS"
    case olderAdults = "OLDER_ADULTS"
    case crossfitFunctional = "CROSSFIT_FUNCTIONAL"
    case other = "OTHER"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PersonalSpecialty: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
