//
// PersonalExerciseVideoState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado público do vídeo. &#x60;NONE&#x60;: sem vídeo — nunca enviado, removido ou sem serviço depois de arquivar o exercício. &#x60;PROCESSING&#x60;: confirmado e em quarentena (recebimento, verificação técnica de contêiner, codec, duração e áudio, e verificação de conteúdo); nada é servido a ninguém. &#x60;READY&#x60;: verificado, com as variantes de leitura. &#x60;REJECTED&#x60;: recusado, com &#x60;rejectionReason&#x60;. A abertura de uma intenção não é estado do vídeo: enquanto a troca não é confirmada, o vídeo vigente continua como estava, e a intenção responde pelo seu próprio prazo. Já confirmar uma troca leva o vídeo a &#x60;PROCESSING&#x60; e o anterior não é mais servido; se o novo virar &#x60;REJECTED&#x60;, o anterior não volta. */
public enum PersonalExerciseVideoState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _none = "NONE"
    case processing = "PROCESSING"
    case ready = "READY"
    case rejected = "REJECTED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PersonalExerciseVideoState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
