//
// PersonalStudentExerciseSetContextView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Uma série, com prescrito, alvo operacional e realizado preservados **separados**. Os três são fatos distintos e nenhum deles é derivado dos outros. Cada um é explicitamente anulável, porque ausência de registro é ausência e nunca vira zero. Nenhum campo carrega observação, texto livre ou juízo sobre a execução. */
public struct PersonalStudentExerciseSetContextView: Codable, JSONEncodable, Hashable {

    public static let setIndexRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var setIndex: Int
    public var status: ExecutedSetStatus
    /** Valores prescritos da série. `null` quando não houve prescrição registrada — e nenhum valor presumido é preenchido para destravar a comparação. */
    public var prescribed: WorkoutSetValues?
    /** Alvo operacional efetivamente apresentado, com a origem da decisão preservada. `null` quando não houve alvo registrado. */
    public var target: ExecutionTargetValues?
    /** Valores realizados. `null` quando a série não foi realizada. */
    public var actual: WorkoutSetValues?

    public init(setIndex: Int, status: ExecutedSetStatus, prescribed: WorkoutSetValues?, target: ExecutionTargetValues?, actual: WorkoutSetValues?) {
        self.setIndex = setIndex
        self.status = status
        self.prescribed = prescribed
        self.target = target
        self.actual = actual
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case setIndex
        case status
        case prescribed
        case target
        case actual
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encode(status, forKey: .status)
        try container.encode(prescribed, forKey: .prescribed)
        try container.encode(target, forKey: .target)
        try container.encode(actual, forKey: .actual)
    }
}


extension PersonalStudentExerciseSetContextView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
