//
// PersonalStudentPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Página da carteira de relacionamentos, sempre de um único estado e paginada exclusivamente por cursor opaco. Não existe offset e o cliente não interpreta o cursor. */
public struct PersonalStudentPage: Codable, JSONEncodable, Hashable {

    public static let nextCursorRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Vínculos da página atual, na ordem definida pelo servidor. */
    public var items: [PersonalStudentListItemView]
    /** Cursor opaco da próxima página; nulo quando não há continuação. */
    public var nextCursor: String?

    public init(items: [PersonalStudentListItemView], nextCursor: String?) {
        self.items = items
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case nextCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}
