//
// PersonalTheme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PersonalTheme: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case dark = "DARK"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PersonalTheme: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
