//
// PlanRelationshipState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado do vínculo na leitura da programação, explícito. &#x60;PAUSED&#x60; encerra a ativação: a leitura responde e não traz ativação. Vínculo **encerrado** não é um valor: a leitura responde &#x60;403 RELATIONSHIP_INACTIVE&#x60;. */
public enum PlanRelationshipState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case active = "ACTIVE"
    case paused = "PAUSED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PlanRelationshipState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
