//
// PlanWeekdaySlot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Um treino da programação por dias da semana e os dias em que ele cai. Um dia da semana pertence a **no máximo um** treino em toda a programação — no máximo um treino por dia — e um treino aparece em **um só** slot; o dia que nenhum slot nomeia é dia sem treino, lido como se lê um dia sem atribuição. A regra de conjunto é do gate e do servidor: &#x60;422 VALIDATION_FAILED&#x60; com &#x60;fieldErrors&#x60; &#x60;WEEKDAY_REPEATED&#x60; ou &#x60;WORKOUT_REPEATED&#x60;. */
public struct PlanWeekdaySlot: Codable, JSONEncodable, Hashable {

    public static let workoutIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let weekdaysRule = ArrayRule(minItems: 1, maxItems: 7, uniqueItems: true)
    /** Treino da versão ativada que cai nestes dias. */
    public var workoutId: String
    /** Dias da semana do treino; um conjunto, sem ordem a preservar. */
    public var weekdays: Set<PlanWeekday>

    public init(workoutId: String, weekdays: Set<PlanWeekday>) {
        self.workoutId = workoutId
        self.weekdays = weekdays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workoutId
        case weekdays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(weekdays, forKey: .weekdays)
    }
}
