//
// PlanActivationMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Como o plano chega ao aluno: por dias da semana com validade (&#x60;WEEKDAYS&#x60;) ou por sequência livre (&#x60;SEQUENCE&#x60;). O personal escolhe um modo por plano. */
public enum PlanActivationMode: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case weekdays = "WEEKDAYS"
    case sequence = "SEQUENCE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PlanActivationMode: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
