//
// PlanActivationChangeView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O resultado de ativar, alterar ou encerrar a programação, dito por efeito. Todo &#x60;outcome&#x60; menos &#x60;ENDED&#x60; traz &#x60;activation&#x60;, a ativação vigente depois da operação. &#x60;REPLACED&#x60; traz &#x60;replacedActivationId&#x60;, a que foi encerrada. &#x60;ENDED&#x60; traz &#x60;endedActivationId&#x60; e **não** traz &#x60;activation&#x60;. &#x60;retiredAssignmentCount&#x60; — quantas atribuições &#x60;AVAILABLE&#x60; futuras materializadas pela ativação anterior foram retiradas — existe em &#x60;REPLACED&#x60;, &#x60;ALTERED&#x60; e &#x60;ENDED&#x60;, onde retirar pode acontecer, e é **ausente** em &#x60;ACTIVATED&#x60;, onde não há o que retirar — o vínculo pausado ou encerrado já retirou, ao encerrar a ativação, as atribuições dela —; presente, &#x60;0&#x60; é \&quot;nenhuma foi retirada\&quot;. Os campos que um &#x60;outcome&#x60; não admite são proibidos, e a regra é do gate. */
public struct PlanActivationChangeView: Codable, JSONEncodable, Hashable {

    public static let studentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let replacedActivationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let endedActivationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let retiredAssignmentCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var studentId: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var asOf: Date
    /** Dia civil de `asOf` no fuso do vínculo; é a referência de `activation.daysUntilEnd`. */
    public var asOfDate: Date
    public var outcome: PlanActivationOutcome
    public var activation: PlanActivationView?
    /** Ativação que esta substituiu e encerrou; só em `REPLACED`. */
    public var replacedActivationId: String?
    /** Ativação que esta operação encerrou; só em `ENDED`. */
    public var endedActivationId: String?
    /** Atribuições `AVAILABLE` futuras, materializadas pela ativação anterior, retiradas na mesma operação; só em `REPLACED`, `ALTERED` e `ENDED`. */
    public var retiredAssignmentCount: Int?

    public init(studentId: String, asOf: Date, asOfDate: Date, outcome: PlanActivationOutcome, activation: PlanActivationView? = nil, replacedActivationId: String? = nil, endedActivationId: String? = nil, retiredAssignmentCount: Int? = nil) {
        self.studentId = studentId
        self.asOf = asOf
        self.asOfDate = asOfDate
        self.outcome = outcome
        self.activation = activation
        self.replacedActivationId = replacedActivationId
        self.endedActivationId = endedActivationId
        self.retiredAssignmentCount = retiredAssignmentCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case studentId
        case asOf
        case asOfDate
        case outcome
        case activation
        case replacedActivationId
        case endedActivationId
        case retiredAssignmentCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(studentId, forKey: .studentId)
        try container.encode(asOf, forKey: .asOf)
        try container.encode(asOfDate, forKey: .asOfDate)
        try container.encode(outcome, forKey: .outcome)
        try container.encodeIfPresent(activation, forKey: .activation)
        try container.encodeIfPresent(replacedActivationId, forKey: .replacedActivationId)
        try container.encodeIfPresent(endedActivationId, forKey: .endedActivationId)
        try container.encodeIfPresent(retiredAssignmentCount, forKey: .retiredAssignmentCount)
    }
}


extension PlanActivationChangeView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if outcome == .unknownDefaultOpenApi { return true }
        return false
    }
}
