//
// PrescribedAlternativeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Distinção obrigatória e sem inferência entre autorizar outra variante do mesmo exercício (&#x60;VARIANT&#x60;) e autorizar outro exercício metodologicamente aceito (&#x60;ALTERNATIVE_EXERCISE&#x60;). A existência de uma alternativa nunca implica equivalência de carga, e os dois conceitos jamais colapsam num campo único. */
public enum PrescribedAlternativeType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case variant = "VARIANT"
    case alternativeExercise = "ALTERNATIVE_EXERCISE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PrescribedAlternativeType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
