//
// PrescriptionDraftSourceKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** De onde o conteúdo do rascunho novo vem, declarado pelo cliente: &#x60;REVISION&#x60; é nova versão do plano **do mesmo aluno**; &#x60;CLONE&#x60; é cópia de plano de **outro** aluno do mesmo personal; &#x60;TEMPLATE&#x60; é cópia de treinos de um modelo. O servidor registra o mesmo valor em &#x60;originKind&#x60; (&#x60;PrescriptionOriginKind&#x60;), junto de &#x60;BLANK&#x60;, que é a ausência de &#x60;source&#x60;. */
public enum PrescriptionDraftSourceKind: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case revision = "REVISION"
    case clone = "CLONE"
    case template = "TEMPLATE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PrescriptionDraftSourceKind: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
