//
// PrescriptionVersionPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Página do histórico de versões publicadas de um aluno, da mais nova para a mais antiga, paginada por cursor opaco. */
public struct PrescriptionVersionPage: Codable, JSONEncodable, Hashable {

    public static let nextCursorRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Versões publicadas, da mais nova para a mais antiga. */
    public var items: [PrescriptionVersionSummary]
    /** Cursor opaco da próxima página; nulo quando não há continuação. */
    public var nextCursor: String?

    public init(items: [PrescriptionVersionSummary], nextCursor: String?) {
        self.items = items
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case nextCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}
