//
// PrescribedEffortType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tipo de esforço alvo declarado pelo personal, quando houver. */
public enum PrescribedEffortType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case rpe = "RPE"
    case rir = "RIR"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension PrescribedEffortType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
