//
// PrescriptionAssignmentAssignPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Atribui um treino de uma versão **publicada** a uma data civil do aluno. &#x60;assignmentId&#x60; é igual ao &#x60;aggregateId&#x60; e nasce no device. A atribuição referencia a versão por identidade e nunca copia o conteúdo prescrito. Uma versão em rascunho é &#x60;FINAL_FAILURE/PRESCRIPTION_VERSION_NOT_PUBLISHED&#x60;; uma segunda atribuição vigente para o mesmo par aluno/data é &#x60;CONFLICT/INVARIANT_VIOLATED&#x60; com a atribuição canônica que ocupa a data. */
public struct PrescriptionAssignmentAssignPayload: Codable, JSONEncodable, Hashable {

    public static let assignmentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let studentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identidade da atribuição, criada no device e igual ao `aggregateId` do envelope. */
    public var assignmentId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var studentId: String
    /** Versão publicada referenciada por identidade; o conteúdo nunca é copiado para o dia. */
    public var prescriptionVersionId: String
    /** Treino dentro da versão publicada. */
    public var workoutId: String
    /** Data civil do aluno a que o treino é atribuído. O servidor é a autoridade do timezone do vínculo e da noção de \"hoje\"; o device não desloca a data. */
    public var localDate: Date

    public init(assignmentId: String, studentId: String, prescriptionVersionId: String, workoutId: String, localDate: Date) {
        self.assignmentId = assignmentId
        self.studentId = studentId
        self.prescriptionVersionId = prescriptionVersionId
        self.workoutId = workoutId
        self.localDate = localDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assignmentId
        case studentId
        case prescriptionVersionId
        case workoutId
        case localDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assignmentId, forKey: .assignmentId)
        try container.encode(studentId, forKey: .studentId)
        try container.encode(prescriptionVersionId, forKey: .prescriptionVersionId)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(localDate, forKey: .localDate)
    }
}
