//
// PrescriptionDraftSet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Série prescrita de um rascunho. Carga e repetições pertencem à série e nunca ao exercício, de modo que quatro séries com cargas distintas preservam os quatro valores. O descanso é o oposto e **não** pertence à série: ele é prescrito uma vez por exercício, em &#x60;PrescriptionDraftExercise.restRange&#x60;, porque é ali que o servidor o guarda. */
public struct PrescriptionDraftSet: Codable, JSONEncodable, Hashable {

    public static let prescribedSetIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let setIndexRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identidade da série, criada pelo personal no device para que a edição offline seja idempotente. */
    public var prescribedSetId: String
    public var setIndex: Int
    public var target: PrescribedTarget?

    public init(prescribedSetId: String, setIndex: Int, target: PrescribedTarget? = nil) {
        self.prescribedSetId = prescribedSetId
        self.setIndex = setIndex
        self.target = target
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case prescribedSetId
        case setIndex
        case target
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(prescribedSetId, forKey: .prescribedSetId)
        try container.encode(setIndex, forKey: .setIndex)
        try container.encodeIfPresent(target, forKey: .target)
    }
}
