//
// PrescriptionDraftSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Resumo do rascunho aberto do aluno: o suficiente para o cartão \&quot;Rascunho em aberto\&quot; e para descartá-lo sem uma leitura a mais. Um vínculo tem no máximo um. &#x60;nextVersionNumber&#x60; é o número que a versão terá se for publicada agora — previsão do servidor, não promessa: a numeração definitiva é emitida na publicação. &#x60;sourcePrescriptionVersionId&#x60; e &#x60;sourceVersionNumber&#x60; aparecem em &#x60;REVISION&#x60;, para a tela dizer \&quot;sobre a v7\&quot;; sem eles o rascunho é a primeira versão ou não nasceu de uma versão deste plano. */
public struct PrescriptionDraftSummary: Codable, JSONEncodable, Hashable {

    public static let draftIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let nameRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let nextVersionNumberRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let sourcePrescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let sourceVersionNumberRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 20, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var draftId: String
    /** Nome da prescrição no rascunho, autorado pelo personal e preservado verbatim. */
    public var name: String
    /** Número previsto da versão; `1` quando o aluno ainda não tem plano publicado, senão o número da vigente mais um. */
    public var nextVersionNumber: Int
    public var originKind: PrescriptionOriginKind
    /** Versão publicada de origem, só em `REVISION`; a origem permanece imutável. Ausente em `BLANK`, `CLONE` e `TEMPLATE`. */
    public var sourcePrescriptionVersionId: String?
    /** Número da versão de origem, em `REVISION`. */
    public var sourceVersionNumber: Int?
    /** Revisão opaca do rascunho, a mesma que `getPersonalPrescriptionDraft` devolve em `ETag`; ecoada em `If-Match` ao descartar ou editar. */
    public var revision: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var updatedAt: Date
    public var workoutCount: Int

    public init(draftId: String, name: String, nextVersionNumber: Int, originKind: PrescriptionOriginKind, sourcePrescriptionVersionId: String? = nil, sourceVersionNumber: Int? = nil, revision: String, updatedAt: Date, workoutCount: Int) {
        self.draftId = draftId
        self.name = name
        self.nextVersionNumber = nextVersionNumber
        self.originKind = originKind
        self.sourcePrescriptionVersionId = sourcePrescriptionVersionId
        self.sourceVersionNumber = sourceVersionNumber
        self.revision = revision
        self.updatedAt = updatedAt
        self.workoutCount = workoutCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case draftId
        case name
        case nextVersionNumber
        case originKind
        case sourcePrescriptionVersionId
        case sourceVersionNumber
        case revision
        case updatedAt
        case workoutCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(draftId, forKey: .draftId)
        try container.encode(name, forKey: .name)
        try container.encode(nextVersionNumber, forKey: .nextVersionNumber)
        try container.encode(originKind, forKey: .originKind)
        try container.encodeIfPresent(sourcePrescriptionVersionId, forKey: .sourcePrescriptionVersionId)
        try container.encodeIfPresent(sourceVersionNumber, forKey: .sourceVersionNumber)
        try container.encode(revision, forKey: .revision)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(workoutCount, forKey: .workoutCount)
    }
}


extension PrescriptionDraftSummary: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if originKind == .unknownDefaultOpenApi { return true }
        return false
    }
}
