//
// PrescriptionActivationSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Resumo da programação vigente do plano, o suficiente para a linha da aba Treinos e para o cartão do plano do aluno. É só leitura e **fechado**: a ativação completa, com os slots, a sequência e a revisão, é &#x60;PlanActivationView&#x60;, lida em &#x60;getPersonalStudentPlanActivation&#x60;; ativar, alterar a programação e encerrar são &#x60;activatePersonalStudentPlan&#x60;, &#x60;updatePersonalStudentPlanActivation&#x60; e &#x60;endPersonalStudentPlanActivation&#x60;, que reusam este vocabulário (&#x60;PlanActivationMode&#x60;, &#x60;PlanWeekday&#x60;). Em &#x60;WEEKDAYS&#x60;, &#x60;weekdays&#x60; traz os dias em que algum treino do plano cai; em &#x60;SEQUENCE&#x60; a chave é omitida, porque a sequência não tem dia. */
public struct PrescriptionActivationSummary: Codable, JSONEncodable, Hashable {

    public static let activationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let weekdaysRule = ArrayRule(minItems: 1, maxItems: 7, uniqueItems: true)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var activationId: String
    public var mode: PlanActivationMode
    /** Data civil no calendário ISO 8601, sem horário ou timezone. */
    public var startDate: Date
    /** Último dia de validade; omitido quando a ativação não tem data de término, e a ausência nunca é lida como vencida. */
    public var endDate: Date?
    /** Dias civis entre o dia de hoje do servidor, no fuso do vínculo, e `endDate`: negativo depois do término, `0` no último dia. Presente somente com `endDate`. É o que o app mostra como \"vence em N dias\", sem depender do relógio nem do fuso do aparelho. */
    public var daysUntilEnd: Int?
    /** Dias da semana programados; presente somente em `WEEKDAYS`. */
    public var weekdays: Set<PlanWeekday>?

    public init(activationId: String, mode: PlanActivationMode, startDate: Date, endDate: Date? = nil, daysUntilEnd: Int? = nil, weekdays: Set<PlanWeekday>? = nil) {
        self.activationId = activationId
        self.mode = mode
        self.startDate = startDate
        self.endDate = endDate
        self.daysUntilEnd = daysUntilEnd
        self.weekdays = weekdays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activationId
        case mode
        case startDate
        case endDate
        case daysUntilEnd
        case weekdays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(activationId, forKey: .activationId)
        try container.encode(mode, forKey: .mode)
        try container.encode(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(daysUntilEnd, forKey: .daysUntilEnd)
        try container.encodeIfPresent(weekdays, forKey: .weekdays)
    }
}


extension PrescriptionActivationSummary: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if mode == .unknownDefaultOpenApi { return true }
        return false
    }
}
