//
// RateWorkoutSessionEffortRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O corpo de &#x60;rateStudentWorkoutSessionEffort&#x60;: só a nota, inteira, de 0 a 10. Fechado de propósito — não há campo de texto, de comentário nem de prazo. */
public struct RateWorkoutSessionEffortRequest: Codable, JSONEncodable, Hashable {

    public static let effortRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10, exclusiveMaximum: false, multipleOf: nil)
    /** A nota de esforço do treino inteiro. `0` é uma nota válida. */
    public var effort: Int

    public init(effort: Int) {
        self.effort = effort
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case effort
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(effort, forKey: .effort)
    }
}
