//
// RecordedPrivacyDecisionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Uma decisão de privacidade como ficou gravada, na versão que o servidor tinha em vigor no instante do commit. A versão é opaca para o cliente e nunca foi proposta por ele; o texto do termo não trafega aqui. Recusas também são gravadas: negar é decisão registrada, não ausência. */
public struct RecordedPrivacyDecisionView: Codable, JSONEncodable, Hashable {

    public static let documentVersionRule = StringRule(minLength: 1, maxLength: 32, pattern: nil)
    public var consentType: StudentConsentType
    public var decision: StudentConsentDecision
    /** Versão do termo resolvida pelo servidor; o cliente não a escolhe nem a valida. */
    public var documentVersion: String

    public init(consentType: StudentConsentType, decision: StudentConsentDecision, documentVersion: String) {
        self.consentType = consentType
        self.decision = decision
        self.documentVersion = documentVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case consentType
        case decision
        case documentVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(consentType, forKey: .consentType)
        try container.encode(decision, forKey: .decision)
        try container.encode(documentVersion, forKey: .documentVersion)
    }
}


extension RecordedPrivacyDecisionView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if consentType == .unknownDefaultOpenApi { return true }
        if decision == .unknownDefaultOpenApi { return true }
        return false
    }
}
