//
// RefreshSessionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RefreshSessionRequest: Codable, JSONEncodable, Hashable {

    public static let refreshTokenRule = StringRule(minLength: 32, maxLength: nil, pattern: nil)
    public static let deviceIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var refreshToken: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var deviceId: String

    public init(refreshToken: String, deviceId: String) {
        self.refreshToken = refreshToken
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case refreshToken
        case deviceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(refreshToken, forKey: .refreshToken)
        try container.encode(deviceId, forKey: .deviceId)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension RefreshSessionRequest: CustomStringConvertible {
    public var description: String { "RefreshSessionRequest([REDACTED])" }
}
