//
// RelationshipSyncView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** &#x60;view&#x60; fechada de &#x60;RELATIONSHIP&#x60;. Carrega somente a identidade do vínculo, o estado em código de máquina e os instantes server-owned; nunca nome, e-mail, telefone, contato ou qualquer conteúdo de treino. */
public struct RelationshipSyncView: Codable, JSONEncodable, Hashable {

    public enum ViewType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case relationship = "RELATIONSHIP"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let counterpartAccountIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var viewType: ViewType
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var relationshipId: String
    /** Identificador público opaco da outra parte do vínculo, do ponto de vista do escopo que recebe a entrada: o aluno para o escopo do personal e o personal para o escopo do aluno. Nunca é nome, e-mail ou contato. */
    public var counterpartAccountId: String
    public var status: RelationshipStatus
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var startedAt: Date
    /** Instante server-owned do encerramento; nulo enquanto o vínculo não terminou. */
    public var endedAt: Date?

    public init(viewType: ViewType, relationshipId: String, counterpartAccountId: String, status: RelationshipStatus, startedAt: Date, endedAt: Date?) {
        self.viewType = viewType
        self.relationshipId = relationshipId
        self.counterpartAccountId = counterpartAccountId
        self.status = status
        self.startedAt = startedAt
        self.endedAt = endedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case viewType
        case relationshipId
        case counterpartAccountId
        case status
        case startedAt
        case endedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(viewType, forKey: .viewType)
        try container.encode(relationshipId, forKey: .relationshipId)
        try container.encode(counterpartAccountId, forKey: .counterpartAccountId)
        try container.encode(status, forKey: .status)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(endedAt, forKey: .endedAt)
    }
}


extension RelationshipSyncView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if viewType == .unknownDefaultOpenApi { return true }
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
