//
// RequestPersonalStudentAnamnesisCompletionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Solicitação de preenchimento dentro do app. Não tem texto, prazo nem canal: o único dado é o vínculo, que precisa ser o vínculo ativo lido. */
public struct RequestPersonalStudentAnamnesisCompletionRequest: Codable, JSONEncodable, Hashable {

    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var relationshipId: String

    public init(relationshipId: String) {
        self.relationshipId = relationshipId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationshipId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relationshipId, forKey: .relationshipId)
    }
}
