//
// ResolveExerciseReferencesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResolveExerciseReferencesRequest: Codable, JSONEncodable, Hashable {

    public static let catalogRefsRule = ArrayRule(minItems: 1, maxItems: 60, uniqueItems: true)
    /** Até 60 referências opacas, as mesmas de `ExerciseCatalogItem.catalogRef`. */
    public var catalogRefs: Set<String>

    public init(catalogRefs: Set<String>) {
        self.catalogRefs = catalogRefs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case catalogRefs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(catalogRefs, forKey: .catalogRefs)
    }
}
