//
// SessionIdentityProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Origem da identidade usada pela sessão atual, projetada no Perfil apenas para que a pessoa reconheça por onde entrou; &#x60;EMAIL&#x60; representa o OTP. Não é capability, não autoriza nada e não é editável por nenhum command publicado. */
public enum SessionIdentityProvider: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case apple = "APPLE"
    case google = "GOOGLE"
    case email = "EMAIL"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SessionIdentityProvider: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
