//
// SetPersonalStudentAnamnesisRequirementRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Escolha explícita do personal. &#x60;relationshipId&#x60; é o vínculo ativo lido em &#x60;getPersonalStudentAnamnesisControls&#x60;; outro vínculo — inclusive um vínculo anterior com o mesmo aluno — é &#x60;409 ANAMNESIS_RELATIONSHIP_MISMATCH&#x60;, sem gravar. */
public struct SetPersonalStudentAnamnesisRequirementRequest: Codable, JSONEncodable, Hashable {

    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var relationshipId: String
    public var requireCurrentCompletion: Bool

    public init(relationshipId: String, requireCurrentCompletion: Bool) {
        self.relationshipId = relationshipId
        self.requireCurrentCompletion = requireCurrentCompletion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationshipId
        case requireCurrentCompletion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relationshipId, forKey: .relationshipId)
        try container.encode(requireCurrentCompletion, forKey: .requireCurrentCompletion)
    }
}
