//
// StartWorkoutSessionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Command de início de sessão. O cliente é a autoridade da identidade (&#x60;sessionId&#x60;); o servidor é a autoridade do instante da sessão, da autorização, do vínculo e da versão prescrita elegível. */
public struct StartWorkoutSessionRequest: Codable, JSONEncodable, Hashable {

    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identidade da sessão, **gerada pelo cliente** antes de qualquer chamada, para que uma sessão iniciada offline mantenha a mesma identidade ao ser sincronizada. Deve ser globalmente única e nunca reutilizada; UUIDv7 é o gerador recomendado, alinhado ao envelope de sync e à baseline dos apps. O valor é opaco: o servidor não atribui semântica a ele e o cliente não infere ordem a partir dele. */
    public var sessionId: String
    /** Treino prescrito que a sessão vai executar, como lido na Home ou no resumo. Em plano em sequência livre, qualquer treino da sequência vigente, e não só o próximo. */
    public var workoutId: String
    /** Versão publicada da prescrição que o cliente leu ao iniciar. A sessão é fixada nela e não migra para uma versão publicada depois. Uma versão que não está atribuída ao aluno é recusada com `PRESCRIPTION_VERSION_NOT_ASSIGNED`, nunca substituída em silêncio. */
    public var prescriptionVersionId: String
    /** Instante do início declarado pelo aparelho, com offset explícito. É aceito e guardado para auditoria, mas não é o instante da sessão: o servidor usa o próprio relógio ao confirmar o início, e é dele que sai o dia civil. Um instante à frente do relógio do servidor além da tolerância é recusado com `CLOCK_SKEW`. */
    public var startedAt: Date
    /** Ponto de entrada aprovado de onde o CTA \"Iniciar treino\" foi acionado. */
    public var source: WorkoutSessionStartSource

    public init(sessionId: String, workoutId: String, prescriptionVersionId: String, startedAt: Date, source: WorkoutSessionStartSource) {
        self.sessionId = sessionId
        self.workoutId = workoutId
        self.prescriptionVersionId = prescriptionVersionId
        self.startedAt = startedAt
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case workoutId
        case prescriptionVersionId
        case startedAt
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(prescriptionVersionId, forKey: .prescriptionVersionId)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(source, forKey: .source)
    }
}


extension StartWorkoutSessionRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if source == .unknownDefaultOpenApi { return true }
        return false
    }
}
