//
// StudentWorkoutSessionResultDeferral.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O adiamento do exercício, como fato, com a posição prescrita e a executada. */
public struct StudentWorkoutSessionResultDeferral: Codable, JSONEncodable, Hashable {

    public static let prescribedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let executedPositionRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var status: DeferralStatus
    public var prescribedPosition: Int
    public var executedPosition: Int

    public init(status: DeferralStatus, prescribedPosition: Int, executedPosition: Int) {
        self.status = status
        self.prescribedPosition = prescribedPosition
        self.executedPosition = executedPosition
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case prescribedPosition
        case executedPosition
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(prescribedPosition, forKey: .prescribedPosition)
        try container.encode(executedPosition, forKey: .executedPosition)
    }
}


extension StudentWorkoutSessionResultDeferral: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
