//
// StudentTodayCardRelationshipView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Identidade do vínculo Personal–Aluno exibido em Hoje, ativo ou pausado. Com o vínculo pausado, &#x60;personal&#x60; é a mesma projeção pública do vínculo ativo: a pausa suspende o treino, não quem acompanha o aluno. Vínculo encerrado ou inexistente nunca alcança esta projeção: a leitura responde &#x60;403 RELATIONSHIP_INACTIVE&#x60; sem confirmar aluno, personal ou prescrição. */
public struct StudentTodayCardRelationshipView: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case active = "ACTIVE"
        case paused = "PAUSED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var relationshipId: String
    /** `ACTIVE` ou `PAUSED`. O vínculo pausado é exibido com o mesmo personal, e a resposta não traz motivo, autoria nem data da pausa. Encerramento é `403`, não um estado exibível aqui. */
    public var status: Status
    public var personal: StudentActivePersonalView

    public init(relationshipId: String, status: Status, personal: StudentActivePersonalView) {
        self.relationshipId = relationshipId
        self.status = status
        self.personal = personal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationshipId
        case status
        case personal
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relationshipId, forKey: .relationshipId)
        try container.encode(status, forKey: .status)
        try container.encode(personal, forKey: .personal)
    }
}


extension StudentTodayCardRelationshipView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
