//
// StudentAnamnesisReadinessFollowUpSection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Desdobramento de cada resposta positiva da triagem: qual condição, se está controlada e se há orientação médica vigente. Uma resposta positiva não impede continuar nem concluir a anamnese. */
public struct StudentAnamnesisReadinessFollowUpSection: Codable, JSONEncodable, Hashable {

    public enum SectionKey: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case readinessScreeningFollowUp = "READINESS_SCREENING_FOLLOW_UP"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let followUpsRule = ArrayRule(minItems: 1, maxItems: 7, uniqueItems: false)
    public var sectionKey: SectionKey
    public var followUps: [StudentReadinessFollowUp]

    public init(sectionKey: SectionKey, followUps: [StudentReadinessFollowUp]) {
        self.sectionKey = sectionKey
        self.followUps = followUps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sectionKey
        case followUps
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sectionKey, forKey: .sectionKey)
        try container.encode(followUps, forKey: .followUps)
    }
}


extension StudentAnamnesisReadinessFollowUpSection: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if sectionKey == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension StudentAnamnesisReadinessFollowUpSection: CustomStringConvertible {
    public var description: String { "StudentAnamnesisReadinessFollowUpSection([REDACTED])" }
}
