//
// StudentOnboardingState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado do onboarding do aluno. &#x60;COMPLETED&#x60; não afirma anamnese concluída nem elegibilidade para prescrição. */
public enum StudentOnboardingState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case notStarted = "NOT_STARTED"
    case inProgress = "IN_PROGRESS"
    case completed = "COMPLETED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentOnboardingState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
