//
// StudentExerciseProgressSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Uma execução da variante: a sessão, o dia civil gravado nela e as séries executadas da variante nessa sessão, na ordem em que foram feitas. */
public struct StudentExerciseProgressSession: Codable, JSONEncodable, Hashable {

    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let setsRule = ArrayRule(minItems: 1, maxItems: 60, uniqueItems: false)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var sessionId: String
    /** O dia civil gravado na sessão, fixado no início dela. */
    public var localDate: Date
    /** As séries executadas da variante nesta sessão; ao menos uma, ou a sessão não é execução da variante. */
    public var sets: [StudentExerciseProgressSet]

    public init(sessionId: String, localDate: Date, sets: [StudentExerciseProgressSet]) {
        self.sessionId = sessionId
        self.localDate = localDate
        self.sets = sets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case localDate
        case sets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(localDate, forKey: .localDate)
        try container.encode(sets, forKey: .sets)
    }
}
