//
// StudentWorkoutSessionResultBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Um bloco combinado do treino, como o personal o montou: o resultado identifica o bloco e a rodada de cada série e **não o achata** em exercícios soltos. &#x60;exerciseExecutionIds&#x60; lista os exercícios do bloco na ordem da rodada. O número de rodadas é o número de séries, igual em todos os exercícios do bloco, e a série N de cada exercício é a rodada N (&#x60;roundIndex&#x60;). */
public struct StudentWorkoutSessionResultBlock: Codable, JSONEncodable, Hashable {

    public static let blockKeyRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let exerciseExecutionIdsRule = ArrayRule(minItems: 2, maxItems: 12, uniqueItems: false)
    /** A identidade do bloco no treino, a mesma que cada exercício do bloco repete em `blockKey`. Identificador de máquina. */
    public var blockKey: String
    public var blockType: PrescribedBlockType
    /** Os exercícios do bloco, na ordem da rodada; cada item é o `exerciseExecutionId` de um item de `exercises[]`. */
    public var exerciseExecutionIds: [String]

    public init(blockKey: String, blockType: PrescribedBlockType, exerciseExecutionIds: [String]) {
        self.blockKey = blockKey
        self.blockType = blockType
        self.exerciseExecutionIds = exerciseExecutionIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockKey
        case blockType
        case exerciseExecutionIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockKey, forKey: .blockKey)
        try container.encode(blockType, forKey: .blockType)
        try container.encode(exerciseExecutionIds, forKey: .exerciseExecutionIds)
    }
}


extension StudentWorkoutSessionResultBlock: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if blockType == .unknownDefaultOpenApi { return true }
        return false
    }
}
