//
// StudentGoalTimeframe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Expectativa declarada pelo aluno. Nunca é compromisso do produto nem promessa de resultado. */
public enum StudentGoalTimeframe: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case upToThreeMonths = "UP_TO_THREE_MONTHS"
    case threeToSixMonths = "THREE_TO_SIX_MONTHS"
    case sixToTwelveMonths = "SIX_TO_TWELVE_MONTHS"
    case overTwelveMonths = "OVER_TWELVE_MONTHS"
    case undefined = "UNDEFINED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentGoalTimeframe: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
