//
// StudentInvitationDeliveryStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado agregado de entrega do e-mail transacional, separado do ciclo de vida e incapaz de invalidar o convite. &#x60;NOT_REQUESTED&#x60; é o convite emitido com &#x60;DO_NOT_SEND&#x60;; &#x60;DELIVERED&#x60; significa que o provedor de envio aceitou a mensagem para entrega e NADA mais — não afirma caixa de entrada, não afirma que escapou de filtro de spam e não afirma leitura, porque o produto não observa nenhuma dessas coisas. */
public enum StudentInvitationDeliveryStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case notRequested = "NOT_REQUESTED"
    case pending = "PENDING"
    case delivered = "DELIVERED"
    case failed = "FAILED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentInvitationDeliveryStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
