//
// StudentActivePersonalView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Projeção do personal para o aluno sob um vínculo ativo: identidade opaca, nome autorado, CREF autodeclarado quando informado e avatar. É deliberadamente fechada e não transporta e-mail, cidade, especialidades, modo de trabalho, preferências ou contadores. O vínculo ativo é a autorização; convite ainda não aceito e vínculo não ativo nunca alcançam esta projeção. A autoria histórica da prescrição usa StudentTodayPersonalRef e permanece separada porque pode apontar para um personal anterior. */
public struct StudentActivePersonalView: Codable, JSONEncodable, Hashable {

    public static let personalIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let displayNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var personalId: String
    /** Nome da pessoa personal trainer, conteúdo autorado preservado verbatim UTF-8. Nunca traduzido, reescrito, truncado nem usado como chave de mensagem, em qualquer locale negociado. */
    public var displayName: String
    public var professionalRegistration: ProfessionalRegistrationView?
    public var avatar: AvatarView

    public init(personalId: String, displayName: String, professionalRegistration: ProfessionalRegistrationView? = nil, avatar: AvatarView) {
        self.personalId = personalId
        self.displayName = displayName
        self.professionalRegistration = professionalRegistration
        self.avatar = avatar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case personalId
        case displayName
        case professionalRegistration
        case avatar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(personalId, forKey: .personalId)
        try container.encode(displayName, forKey: .displayName)
        try container.encodeIfPresent(professionalRegistration, forKey: .professionalRegistration)
        try container.encode(avatar, forKey: .avatar)
    }
}
