//
// StudentWorkoutSessionHistoryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Um treino terminado do histórico, o que a linha de treino feito e os recordes recentes mostram: o nome, o dia, a duração, as séries feitas de previstas e os recordes resumidos. Entra a sessão &#x60;COMPLETED&#x60; ou &#x60;ABANDONED&#x60; com **ao menos uma série executada** (&#x60;completedSetCount&#x60; começa em 1). Fato registrado: não muda quando o personal publica outra versão. &#x60;localDate&#x60; é o dia civil gravado na sessão, fixado no início dela, e não muda se o aluno trocar de personal ou de fuso. &#x60;completedSetCount&#x60; são as séries executadas, inteiras ou parciais, e &#x60;totalSetCount&#x60; as séries do treino na versão da sessão, as mesmas &#x60;setsDone&#x60; e &#x60;setsPlanned&#x60; do resultado. &#x60;recordCount&#x60; é o tamanho de &#x60;records&#x60; em &#x60;getStudentWorkoutSessionResult&#x60;, pela mesma projeção; é **nulo** quando a projeção não pôde ser lida nesta resposta, e então &#x60;records&#x60; vem vazio — nulo nunca é lido como zero. &#x60;records&#x60; resume até 3 recordes da sessão, os primeiros do resultado dela. Não há volume, nota de esforço, relato de desconforto, escore nem percentual de aderência: o resultado completo abre por &#x60;sessionId&#x60;. */
public struct StudentWorkoutSessionHistoryItem: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case completed = "COMPLETED"
        case abandoned = "ABANDONED"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let durationSecondsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let completedSetCountRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalSetCountRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let recordCountRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let recordsRule = ArrayRule(minItems: nil, maxItems: 3, uniqueItems: false)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var sessionId: String
    /** O nome do treino executado, como estava na versão que originou a sessão. Conteúdo do domínio preservado verbatim. */
    public var workoutName: String
    /** O dia civil gravado na sessão, fixado no início dela; é com ele que `from` e `to` comparam. */
    public var localDate: Date
    /** O instante do servidor em que a sessão começou; a ordem do histórico. */
    public var startedAt: Date
    /** O instante do servidor em que a sessão terminou, em qualquer desfecho. */
    public var endedAt: Date
    /** A duração do início ao término, em segundos; igual a `endedAt` menos `startedAt`. */
    public var durationSeconds: Int
    /** `COMPLETED` ou `ABANDONED`; a sessão aberta não entra no histórico. `ABANDONED` é o treino descartado com série executada, e o app o marca como não concluído. */
    public var status: Status
    public var endedBy: WorkoutSessionEndedBy
    /** As séries executadas, inteiras ou parciais; ao menos uma, ou a sessão não entra no histórico. */
    public var completedSetCount: Int
    /** As séries do treino na versão da sessão. */
    public var totalSetCount: Int
    /** Quantos recordes a sessão bateu, pela mesma projeção do resultado. Nulo quando a projeção não pôde ser lida nesta resposta; nunca é lido como zero. */
    public var recordCount: Int?
    /** Até 3 recordes da sessão, resumidos, os primeiros do `records` do resultado dela. Vazia quando a sessão não bateu recorde e quando `recordCount` é nulo. */
    public var records: [StudentProgressRecord]

    public init(sessionId: String, workoutName: String, localDate: Date, startedAt: Date, endedAt: Date, durationSeconds: Int, status: Status, endedBy: WorkoutSessionEndedBy, completedSetCount: Int, totalSetCount: Int, recordCount: Int?, records: [StudentProgressRecord]) {
        self.sessionId = sessionId
        self.workoutName = workoutName
        self.localDate = localDate
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.durationSeconds = durationSeconds
        self.status = status
        self.endedBy = endedBy
        self.completedSetCount = completedSetCount
        self.totalSetCount = totalSetCount
        self.recordCount = recordCount
        self.records = records
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case workoutName
        case localDate
        case startedAt
        case endedAt
        case durationSeconds
        case status
        case endedBy
        case completedSetCount
        case totalSetCount
        case recordCount
        case records
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(workoutName, forKey: .workoutName)
        try container.encode(localDate, forKey: .localDate)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(endedAt, forKey: .endedAt)
        try container.encode(durationSeconds, forKey: .durationSeconds)
        try container.encode(status, forKey: .status)
        try container.encode(endedBy, forKey: .endedBy)
        try container.encode(completedSetCount, forKey: .completedSetCount)
        try container.encode(totalSetCount, forKey: .totalSetCount)
        try container.encode(recordCount, forKey: .recordCount)
        try container.encode(records, forKey: .records)
    }
}


extension StudentWorkoutSessionHistoryItem: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        if endedBy == .unknownDefaultOpenApi { return true }
        return false
    }
}
