//
// StudentWorkoutSessionResultDiscomfort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O relato de desconforto do exercício, como fato: **só a região e a intensidade**. A sensação e o texto livre do relato não são devolvidos por esta leitura, que não pede mais que o fato, e nenhum campo diz que existe texto. */
public struct StudentWorkoutSessionResultDiscomfort: Codable, JSONEncodable, Hashable {

    public enum Area: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case headNeck = "HEAD_NECK"
        case shoulder = "SHOULDER"
        case arm = "ARM"
        case elbow = "ELBOW"
        case wristHand = "WRIST_HAND"
        case chest = "CHEST"
        case back = "BACK"
        case hip = "HIP"
        case thigh = "THIGH"
        case knee = "KNEE"
        case leg = "LEG"
        case ankleFoot = "ANKLE_FOOT"
        case other = "OTHER"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let intensityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10, exclusiveMaximum: false, multipleOf: nil)
    public var area: Area
    public var intensity: Int

    public init(area: Area, intensity: Int) {
        self.area = area
        self.intensity = intensity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case area
        case intensity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(area, forKey: .area)
        try container.encode(intensity, forKey: .intensity)
    }
}


extension StudentWorkoutSessionResultDiscomfort: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if area == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension StudentWorkoutSessionResultDiscomfort: CustomStringConvertible {
    public var description: String { "StudentWorkoutSessionResultDiscomfort([REDACTED])" }
}
