//
// StudentReferenceLoadsView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Cargas de referência de um aluno, uma por variante, com o instante &#x60;asOf&#x60; em que a estimativa foi calculada. Variante ausente da lista não tem referência confirmada nem série elegível: a ausência nunca é zero. */
public struct StudentReferenceLoadsView: Codable, JSONEncodable, Hashable {

    public static let studentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var studentId: String
    /** Instante do servidor em que a leitura, e portanto a estimativa, foi calculada. */
    public var asOf: Date
    /** Uma por variante, sem repetição de `variantId`; todas, sem corte e sem paginação. */
    public var items: [StudentReferenceLoadItem]

    public init(studentId: String, asOf: Date, items: [StudentReferenceLoadItem]) {
        self.studentId = studentId
        self.asOf = asOf
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case studentId
        case asOf
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(studentId, forKey: .studentId)
        try container.encode(asOf, forKey: .asOf)
        try container.encode(items, forKey: .items)
    }
}
