//
// StudentConsistencyView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A consistência semanal do aluno, uma projeção (&#x60;origin: PROJECTION&#x60;) das sessões concluídas e dos dias da ativação vigente. **Sem escore, sem percentual e sem sequência de dias**: nenhum campo carrega nota, taxa, razão entre feitos e previstos, contagem de dias seguidos ou sem treinar, semana perdida nem meta do produto. &#x60;planMode&#x60; é o modo da ativação vigente em &#x60;asOf&#x60; e é **ausente** quando não há ativação vigente. &#x60;weeks&#x60; vem da mais antiga à corrente, seguidas e sem lacuna. */
public struct StudentConsistencyView: Codable, JSONEncodable, Hashable {

    public enum Origin: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case projection = "PROJECTION"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let weeksRule = ArrayRule(minItems: 1, maxItems: 12, uniqueItems: false)
    /** O modo da ativação vigente em `asOf`. Ausente quando não há ativação vigente. */
    public var planMode: PlanActivationMode?
    /** O instante do servidor em que a leitura foi calculada; nunca o relógio do aparelho. */
    public var asOf: Date
    /** O selo de projeção. */
    public var origin: Origin
    /** As semanas pedidas, da mais antiga à corrente (a última), consecutivas. */
    public var weeks: [StudentConsistencyWeek]

    public init(planMode: PlanActivationMode? = nil, asOf: Date, origin: Origin, weeks: [StudentConsistencyWeek]) {
        self.planMode = planMode
        self.asOf = asOf
        self.origin = origin
        self.weeks = weeks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case planMode
        case asOf
        case origin
        case weeks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(planMode, forKey: .planMode)
        try container.encode(asOf, forKey: .asOf)
        try container.encode(origin, forKey: .origin)
        try container.encode(weeks, forKey: .weeks)
    }
}


extension StudentConsistencyView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if planMode == .unknownDefaultOpenApi { return true }
        if origin == .unknownDefaultOpenApi { return true }
        return false
    }
}
