//
// StudentTodayWorkoutCardStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado do cartão do treino de hoje, decidido pelo servidor e nunca inferido pelo cliente; enum próprio do cartão. &#x60;AWAITING_FIRST_PLAN&#x60;: vínculo ativo e nenhuma ativação jamais nesta relação; publicar uma versão sem ativá-la não sai daqui. &#x60;PLAN_NOT_STARTED&#x60;: nenhuma ativação vigente hoje, uma ativação com início depois de hoje (&#x60;planStartsOn&#x60;) e nenhuma atribuição avulsa para hoje. &#x60;NO_WORKOUT_ASSIGNED&#x60;: já houve ativação nesta relação e nenhuma está vigente nem por começar, ou a sequência vigente não tem treino. &#x60;REST_DAY&#x60;: ativação por dias da semana vigente e hoje sem treino. &#x60;WORKOUT_AVAILABLE&#x60;: há treino para hoje e nenhuma sessão aberta; a ação é iniciar. &#x60;SESSION_IN_PROGRESS&#x60;: há sessão aberta, em andamento ou interrompida (&#x60;openSession.status&#x60;); a ação nunca é iniciar outra. &#x60;WORKOUT_COMPLETED&#x60;: o treino de hoje foi concluído. &#x60;TRAINING_PAUSED&#x60;: o vínculo está pausado; nome técnico, sem motivo, autoria nem data da pausa — a tela não diz que houve pausa. Não existe estado de dia já usado: a sessão descartada não ocupa o dia. */
public enum StudentTodayWorkoutCardStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case noWorkoutAssigned = "NO_WORKOUT_ASSIGNED"
    case restDay = "REST_DAY"
    case workoutAvailable = "WORKOUT_AVAILABLE"
    case sessionInProgress = "SESSION_IN_PROGRESS"
    case workoutCompleted = "WORKOUT_COMPLETED"
    case awaitingFirstPlan = "AWAITING_FIRST_PLAN"
    case planNotStarted = "PLAN_NOT_STARTED"
    case trainingPaused = "TRAINING_PAUSED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentTodayWorkoutCardStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
