//
// StudentAnamnesisPreviousVersionsGrantView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Quais versões de vínculos anteriores o aluno autoriza, uma a uma, ao personal do vínculo atual. Antes de qualquer escolha o conjunto é vazio: nada vem marcado nem é herdado. Autorizar não autoriza versões futuras, não alcança a ficha atual — cujo acesso decorre do aceite real do termo —, não satisfaz o preenchimento obrigatório dela e não faz nascer item na fila do personal. */
public struct StudentAnamnesisPreviousVersionsGrantView: Codable, JSONEncodable, Hashable {

    public static let relationshipIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let versionIdsRule = ArrayRule(minItems: nil, maxItems: 200, uniqueItems: true)
    /** Vínculo destinatário, o vínculo atual do aluno. */
    public var relationshipId: String
    /** Revisão opaca do conjunto, igual ao `ETag`; `If-Match` a ecoa ao alterá-lo. */
    public var revision: String
    /** Versões autorizadas, em ordem crescente de identificador. */
    public var versionIds: Set<String>
    /** Instante do servidor da última escolha, ausente antes da primeira. */
    public var updatedAt: Date?

    public init(relationshipId: String, revision: String, versionIds: Set<String>, updatedAt: Date? = nil) {
        self.relationshipId = relationshipId
        self.revision = revision
        self.versionIds = versionIds
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationshipId
        case revision
        case versionIds
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relationshipId, forKey: .relationshipId)
        try container.encode(revision, forKey: .revision)
        try container.encode(versionIds, forKey: .versionIds)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}
