//
// StudentInvitationDeliveryAttemptView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Uma tentativa de entrega do e-mail transacional do convite. O servidor publica somente o que o provedor de envio lhe devolveu: a tentativa foi aceita para entrega ou falhou. NENHUM estado aqui afirma que a mensagem chegou à caixa de entrada, que escapou de filtro de spam ou que foi lida — o produto não observa isso e não o inventa. Falha de entrega nunca invalida o convite. */
public struct StudentInvitationDeliveryAttemptView: Codable, JSONEncodable, Hashable {

    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var attemptedAt: Date
    public var status: StudentInvitationDeliveryAttemptStatus
    public var failureReason: StudentInvitationDeliveryFailureReason?

    public init(attemptedAt: Date, status: StudentInvitationDeliveryAttemptStatus, failureReason: StudentInvitationDeliveryFailureReason? = nil) {
        self.attemptedAt = attemptedAt
        self.status = status
        self.failureReason = failureReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attemptedAt
        case status
        case failureReason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attemptedAt, forKey: .attemptedAt)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(failureReason, forKey: .failureReason)
    }
}


extension StudentInvitationDeliveryAttemptView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        if failureReason == .unknownDefaultOpenApi { return true }
        return false
    }
}
