//
// StudentInvitationDeliveryFailureReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Classe da falha de uma tentativa, presente apenas quando o desfecho é &#x60;FAILED&#x60;. O vocabulário é neutro quanto ao provedor e nunca transporta mensagem, cabeçalho ou identificador de terceiro. &#x60;DESTINATION_REJECTED&#x60; não confirma existência de conta ou destino: é o desfecho técnico da tentativa, não um veredito sobre o aluno. */
public enum StudentInvitationDeliveryFailureReason: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case providerRejected = "PROVIDER_REJECTED"
    case providerUnavailable = "PROVIDER_UNAVAILABLE"
    case destinationRejected = "DESTINATION_REJECTED"
    case suppressed = "SUPPRESSED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentInvitationDeliveryFailureReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
