//
// StudentExerciseProgressVariant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Uma variante de um exercício que o aluno executou, no contexto de equipamento em que a executou: o par é a chave de comparabilidade, e cada par é um item. Resume quando foi a última vez e quantas vezes; não traz carga, repetição nem recorde, e variantes diferentes nunca são somadas, comparadas nem ordenadas por desempenho. &#x60;executionCount&#x60; conta as sessões em que o par teve ao menos uma série executada. */
public struct StudentExerciseProgressVariant: Codable, JSONEncodable, Hashable {

    public static let variantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let variantLabelRule = StringRule(minLength: 1, maxLength: 120, pattern: nil)
    public static let equipmentContextKeyRule = StringRule(minLength: 1, maxLength: 64, pattern: nil)
    public static let executionCountRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var variantId: String
    /** O rótulo da variante, preservado verbatim — o que o seletor da evolução mostra (`Barra`, `Halteres`). Para o exercício do catálogo, que tem uma variante só, é o `displayName`. */
    public var variantLabel: String
    /** O contexto de equipamento que fecha a chave de comparabilidade com a variante. Código de máquina estável e opaco, nunca nome de aparelho exibível nem texto a interpretar. O cliente o devolve exatamente como veio, em `equipmentContextKey` de `getStudentExerciseProgress`, para ler o mesmo par, e nunca o deriva, completa ou presume: do lado do cliente não existe equipamento padrão. **Ausente** só quando o servidor não publica contexto para o par; ausência é ausência, e o pedido do mesmo par também o omite. */
    public var equipmentContextKey: String?
    /** O dia civil (`localDate`) da sessão mais recente em que o par foi executado. */
    public var lastExecutedOn: Date
    /** Quantas sessões executaram o par; ao menos uma, ou o par não entra na lista. */
    public var executionCount: Int

    public init(variantId: String, variantLabel: String, equipmentContextKey: String? = nil, lastExecutedOn: Date, executionCount: Int) {
        self.variantId = variantId
        self.variantLabel = variantLabel
        self.equipmentContextKey = equipmentContextKey
        self.lastExecutedOn = lastExecutedOn
        self.executionCount = executionCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case variantId
        case variantLabel
        case equipmentContextKey
        case lastExecutedOn
        case executionCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(variantId, forKey: .variantId)
        try container.encode(variantLabel, forKey: .variantLabel)
        try container.encodeIfPresent(equipmentContextKey, forKey: .equipmentContextKey)
        try container.encode(lastExecutedOn, forKey: .lastExecutedOn)
        try container.encode(executionCount, forKey: .executionCount)
    }
}
