//
// StudentTodayHeaderView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Cabeçalho independente da tela Hoje, com data e identidade separadas da copy. A ausência legítima de nome autorado não torna a região indisponível. */
public struct StudentTodayHeaderView: Codable, JSONEncodable, Hashable {

    public static let timeZoneRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let greetingRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let displayNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Data civil no calendário ISO 8601, sem horário ou timezone. */
    public var date: Date
    /** Identificador de timezone IANA, por exemplo `America/Sao_Paulo`. */
    public var timeZone: String
    /** Saudação do período do dia, copy do servidor negociada por `Accept-Language` e calculada **no fuso do vínculo** (`timeZone`): `Bom dia` de 00:00 a 11:59, `Boa tarde` de 12:00 a 17:59 e `Boa noite` de 18:00 a 23:59 — `Good morning`, `Good afternoon` e `Good evening`. Vem **sem pontuação**: o cliente compõe a linha com `displayName` como componente separado e põe os separadores do locale; nunca interpola o nome nesta mensagem nem a usa como chave de catálogo. */
    public var greeting: String
    /** O nome que o aluno informou no próprio perfil (`getStudentProfile`, `saveStudentProfile`), como ele escreveu, de 1 a 60 caracteres, ou nulo enquanto não informou e depois de apagá-lo. Nunca é derivado do rótulo privado do convite, do e-mail ou de atributos do provedor. */
    public var displayName: String?

    public init(date: Date, timeZone: String, greeting: String, displayName: String?) {
        self.date = date
        self.timeZone = timeZone
        self.greeting = greeting
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case timeZone
        case greeting
        case displayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(timeZone, forKey: .timeZone)
        try container.encode(greeting, forKey: .greeting)
        try container.encode(displayName, forKey: .displayName)
    }
}
