//
// StudentTrainingPlanState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado do plano quando a leitura de treino a fazer responde sem treino por causa do vínculo. &#x60;TRAINING_PAUSED&#x60;: vínculo pausado; nome técnico, sem motivo, autoria nem data da pausa — a tela não diz que houve pausa. */
public enum StudentTrainingPlanState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case trainingPaused = "TRAINING_PAUSED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentTrainingPlanState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
