//
// StudentPreferredTimeOfDay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StudentPreferredTimeOfDay: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case morning = "MORNING"
    case afternoon = "AFTERNOON"
    case evening = "EVENING"
    case night = "NIGHT"
    case flexible = "FLEXIBLE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentPreferredTimeOfDay: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
