//
// StudentAnamnesisStateView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado da anamnese do próprio aluno, com o rascunho privado que ele pode retomar. O rascunho pertence ao aluno e nunca é projetado para o personal. */
public struct StudentAnamnesisStateView: Codable, JSONEncodable, Hashable {

    public var state: StudentAnamnesisState
    /** Verdadeiro somente quando existe ao menos uma versão concluída; rascunho não conta. */
    public var completed: Bool
    /** Versões concluídas, da mais recente para a mais antiga; nenhuma é reescrita. */
    public var completedVersions: [StudentAnamnesisVersionRef]
    public var latestCompletedVersion: StudentAnamnesisVersionView?
    public var draft: StudentAnamnesisDraftView

    public init(state: StudentAnamnesisState, completed: Bool, completedVersions: [StudentAnamnesisVersionRef], latestCompletedVersion: StudentAnamnesisVersionView? = nil, draft: StudentAnamnesisDraftView) {
        self.state = state
        self.completed = completed
        self.completedVersions = completedVersions
        self.latestCompletedVersion = latestCompletedVersion
        self.draft = draft
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case state
        case completed
        case completedVersions
        case latestCompletedVersion
        case draft
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(state, forKey: .state)
        try container.encode(completed, forKey: .completed)
        try container.encode(completedVersions, forKey: .completedVersions)
        try container.encodeIfPresent(latestCompletedVersion, forKey: .latestCompletedVersion)
        try container.encode(draft, forKey: .draft)
    }
}


extension StudentAnamnesisStateView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if state == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension StudentAnamnesisStateView: CustomStringConvertible {
    public var description: String { "StudentAnamnesisStateView([REDACTED])" }
}
