//
// StudentConsentDecision.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Decisão explícita da pessoa sobre um item. Ausência **não** é decisão: um item sem decisão torna o pedido incompleto, e não é lido como recusa silenciosa nem como concessão silenciosa. */
public enum StudentConsentDecision: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case granted = "GRANTED"
    case declined = "DECLINED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentConsentDecision: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
