//
// StudentReferenceLoadItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A carga de referência de **uma variante** do aluno: o valor confirmado, a estimativa sugerida, ou os dois. Um item sem nenhum dos dois não existe — a variante nessa situação simplesmente não aparece. Valor confirmado e estimativa são blocos separados e nunca se fundem: a estimativa não substitui a referência confirmada, e a confirmada não é recalculada por ela. */
public struct StudentReferenceLoadItem: Codable, JSONEncodable, Hashable {

    public static let variantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Variante a que a referência pertence; é a identidade da comparabilidade, nunca o exercício. */
    public var variantId: String
    public var confirmed: ReferenceLoadConfirmed?
    public var estimate: ReferenceLoadEstimate?

    public init(variantId: String, confirmed: ReferenceLoadConfirmed? = nil, estimate: ReferenceLoadEstimate? = nil) {
        self.variantId = variantId
        self.confirmed = confirmed
        self.estimate = estimate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case variantId
        case confirmed
        case estimate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(variantId, forKey: .variantId)
        try container.encodeIfPresent(confirmed, forKey: .confirmed)
        try container.encodeIfPresent(estimate, forKey: .estimate)
    }
}
