//
// StudentInvitationCapability.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StudentInvitationCapability: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case receiveWorkouts = "RECEIVE_WORKOUTS"
    case trackExecution = "TRACK_EXECUTION"
    case trackProgress = "TRACK_PROGRESS"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentInvitationCapability: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
