//
// StudentInvitationAcceptanceContextRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StudentInvitationAcceptanceContextRequest: Codable, JSONEncodable, Hashable {

    public static let tokenRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let invitationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Bearer secret opaco do convite; nunca deve ser enviado em path, query, logs ou analytics. Apresentá-lo aqui não consome o convite. */
    public var token: String
    /** Conferência cruzada **opcional**. Quando presente tem de ser o convite daquele token; divergir responde `404 INVITATION_NOT_FOUND`. */
    public var invitationId: String?

    public init(token: String, invitationId: String? = nil) {
        self.token = token
        self.invitationId = invitationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case invitationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(invitationId, forKey: .invitationId)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension StudentInvitationAcceptanceContextRequest: CustomStringConvertible {
    public var description: String { "StudentInvitationAcceptanceContextRequest([REDACTED])" }
}
