//
// StudentOnboardingStepView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StudentOnboardingStepView: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case notStarted = "NOT_STARTED"
        case inProgress = "IN_PROGRESS"
        case completed = "COMPLETED"
        case notApplicable = "NOT_APPLICABLE"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var key: StudentAnamnesisSectionKey
    public var status: Status

    public init(key: StudentAnamnesisSectionKey, status: Status) {
        self.key = key
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(status, forKey: .status)
    }
}


extension StudentOnboardingStepView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if key == .unknownDefaultOpenApi { return true }
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
