//
// StudentAnamnesisDraftView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Rascunho privado do aluno. Existe desde antes da primeira seção salva, para que a &#x60;revision&#x60; do compare-and-set esteja sempre disponível. Salvar aqui não conclui, não cria versão e não notifica o personal. */
public struct StudentAnamnesisDraftView: Codable, JSONEncodable, Hashable {

    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Revisão opaca do rascunho e **única** precondição desta superfície: é ela que o `ETag` da leitura publica e que `If-Match` ecoa ao salvar seção e ao concluir. */
    public var revision: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var updatedAt: Date
    /** Seções já preenchidas, tipadas; uma seção ausente permanece ausente e nunca vira valor vazio. */
    public var sections: [StudentAnamnesisSection]

    public init(revision: String, updatedAt: Date, sections: [StudentAnamnesisSection]) {
        self.revision = revision
        self.updatedAt = updatedAt
        self.sections = sections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revision
        case updatedAt
        case sections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revision, forKey: .revision)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(sections, forKey: .sections)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension StudentAnamnesisDraftView: CustomStringConvertible {
    public var description: String { "StudentAnamnesisDraftView([REDACTED])" }
}
