//
// StudentAnamnesisBodyRegionLimitation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StudentAnamnesisBodyRegionLimitation: Codable, JSONEncodable, Hashable {

    public enum Intensity: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case mild = "MILD"
        case moderate = "MODERATE"
        case severe = "SEVERE"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let notesRule = StringRule(minLength: 1, maxLength: 200, pattern: nil)
    public var bodyRegion: StudentBodyRegion
    public var intensity: Intensity
    public var notes: String?

    public init(bodyRegion: StudentBodyRegion, intensity: Intensity, notes: String? = nil) {
        self.bodyRegion = bodyRegion
        self.intensity = intensity
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bodyRegion
        case intensity
        case notes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bodyRegion, forKey: .bodyRegion)
        try container.encode(intensity, forKey: .intensity)
        try container.encodeIfPresent(notes, forKey: .notes)
    }
}


extension StudentAnamnesisBodyRegionLimitation: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if bodyRegion == .unknownDefaultOpenApi { return true }
        if intensity == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension StudentAnamnesisBodyRegionLimitation: CustomStringConvertible {
    public var description: String { "StudentAnamnesisBodyRegionLimitation([REDACTED])" }
}
