//
// StudentWorkoutSessionRecordType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O critério do recorde, e só estes três. &#x60;MAX_LOAD&#x60;: a maior carga da chave, em série com ao menos uma repetição. &#x60;MAX_REPS_AT_LOAD&#x60;: mais repetições numa carga que a base já tinha usado; com o peso do corpo, a \&quot;mesma carga\&quot; é \&quot;sem carga\&quot;. &#x60;MAX_DURATION&#x60;: a maior duração em série por tempo, na mesma carga ou ambas sem carga. */
public enum StudentWorkoutSessionRecordType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case maxLoad = "MAX_LOAD"
    case maxRepsAtLoad = "MAX_REPS_AT_LOAD"
    case maxDuration = "MAX_DURATION"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentWorkoutSessionRecordType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
