//
// StudentInvitationAcceptanceContextView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tudo o que precede o vínculo, numa leitura só: quem convidou, o que falta provar sobre o endereço convidado, o veredito de idade, o catálogo de privacidade vigente e a troca, quando houver. **Nada aqui cria, consome ou altera estado.** &#x60;revision&#x60; é a revisão opaca deste contexto, idêntica ao &#x60;ETag&#x60; da resposta e exatamente o que &#x60;If-Match&#x60; do aceite exige. */
public struct StudentInvitationAcceptanceContextView: Codable, JSONEncodable, Hashable {

    public static let invitationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let privacyCatalogRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var invitationId: String
    /** Validador opaco deste contexto. O cliente o ecoa em `If-Match` ao confirmar e nunca o interpreta, ordena ou constrói. */
    public var revision: String
    public var personal: InvitationPersonalView
    public var emailOwnership: InvitationEmailOwnershipContextView
    public var ageAssurance: StudentAgeAssuranceContextView
    /** Catálogo vigente, na íntegra. O aceite exige decisão explícita para **cada** item desta lista; cobri-la parcialmente é `422 PRIVACY_DECISIONS_INCOMPLETE`. */
    public var privacyCatalog: [StudentPrivacyCatalogItemView]
    public var replacement: StudentRelationshipReplacementContextView

    public init(invitationId: String, revision: String, personal: InvitationPersonalView, emailOwnership: InvitationEmailOwnershipContextView, ageAssurance: StudentAgeAssuranceContextView, privacyCatalog: [StudentPrivacyCatalogItemView], replacement: StudentRelationshipReplacementContextView) {
        self.invitationId = invitationId
        self.revision = revision
        self.personal = personal
        self.emailOwnership = emailOwnership
        self.ageAssurance = ageAssurance
        self.privacyCatalog = privacyCatalog
        self.replacement = replacement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invitationId
        case revision
        case personal
        case emailOwnership
        case ageAssurance
        case privacyCatalog
        case replacement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invitationId, forKey: .invitationId)
        try container.encode(revision, forKey: .revision)
        try container.encode(personal, forKey: .personal)
        try container.encode(emailOwnership, forKey: .emailOwnership)
        try container.encode(ageAssurance, forKey: .ageAssurance)
        try container.encode(privacyCatalog, forKey: .privacyCatalog)
        try container.encode(replacement, forKey: .replacement)
    }
}
