//
// StudentProgressRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Um recorde como cartão de progresso: o critério (&#x60;type&#x60;), o rótulo do exercício e o valor, na unidade em que foi gravado. É **projeção** determinística e reconstruível dos fatos (&#x60;origin: PROJECTION&#x60;), a mesma de &#x60;StudentWorkoutSessionRecord&#x60;, sem a série nem o valor anterior que o resultado da sessão carrega: o critério por extenso com o valor é o que o cartão mostra, e o detalhe de cada um abre no resultado da sessão. **Chave de comparabilidade:** variante executada + contexto de equipamento + a unidade de carga; a mesma variante em &#x60;KG&#x60; e em &#x60;LB&#x60; são séries separadas, o servidor não compara por massa e substituição usa a variante realmente executada. Só as séries &#x60;WORKING&#x60; e &#x60;TO_FAILURE&#x60; valem; &#x60;WARM_UP&#x60;, &#x60;DROP_SET&#x60; e a série pulada ficam fora, e igual não é recorde. &#x60;BODYWEIGHT&#x60; só produz &#x60;MAX_REPS_AT_LOAD&#x60; e &#x60;MAX_DURATION&#x60;, nunca &#x60;MAX_LOAD&#x60;; &#x60;LEVEL&#x60; produz &#x60;MAX_LOAD&#x60; na unidade &#x60;LEVEL&#x60;, nunca convertido nem somado a kg. A tela converte só para exibir. Não existe carga máxima estimada para o aluno: nenhum campo deste schema a carrega. */
public struct StudentProgressRecord: Codable, JSONEncodable, Hashable {

    public enum LoadUnit: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case kg = "KG"
        case lb = "LB"
        case bodyweight = "BODYWEIGHT"
        case level = "LEVEL"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let exerciseLabelRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let loadValueRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let repsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let durationSecondsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var type: StudentWorkoutSessionRecordType
    /** O selo de projeção. */
    public var origin: String
    /** O rótulo do exercício, o `displayName` que o personal deu na prescrição, preservado verbatim e invariante de locale. */
    public var exerciseLabel: String
    /** A carga do recorde, na unidade gravada. Ausente com `BODYWEIGHT` e quando o recorde de duração não tem carga. */
    public var loadValue: Double?
    /** A unidade da carga do recorde, como gravada. Ausente quando o recorde de duração não tem carga. */
    public var loadUnit: LoadUnit?
    /** As repetições do recorde `MAX_REPS_AT_LOAD`; ausente nos outros. */
    public var reps: Int?
    /** A duração do recorde `MAX_DURATION`, em segundos; ausente nos outros. */
    public var durationSeconds: Int?

    public init(type: StudentWorkoutSessionRecordType, origin: String, exerciseLabel: String, loadValue: Double? = nil, loadUnit: LoadUnit? = nil, reps: Int? = nil, durationSeconds: Int? = nil) {
        self.type = type
        self.origin = origin
        self.exerciseLabel = exerciseLabel
        self.loadValue = loadValue
        self.loadUnit = loadUnit
        self.reps = reps
        self.durationSeconds = durationSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case origin
        case exerciseLabel
        case loadValue
        case loadUnit
        case reps
        case durationSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(origin, forKey: .origin)
        try container.encode(exerciseLabel, forKey: .exerciseLabel)
        try container.encodeIfPresent(loadValue, forKey: .loadValue)
        try container.encodeIfPresent(loadUnit, forKey: .loadUnit)
        try container.encodeIfPresent(reps, forKey: .reps)
        try container.encodeIfPresent(durationSeconds, forKey: .durationSeconds)
    }
}


extension StudentProgressRecord: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if loadUnit == .unknownDefaultOpenApi { return true }
        return false
    }
}
