//
// StudentPrescriptionEligibilityBlockingReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** &#x60;MEDICAL_CLEARANCE_REQUIRED&#x60; corresponde à prontidão aguardando liberação e **não** bloqueia concluir a anamnese. &#x60;GUARDIAN_AUTHORIZATION_REQUIRED&#x60; é o **único** ponto de contato contratual da autorização de responsável: não existe operação para conceder, revogar, consultar ou convidar, e nenhum campo desta API expõe identidade, nome ou contato do responsável. */
public enum StudentPrescriptionEligibilityBlockingReason: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case relationshipNotActive = "RELATIONSHIP_NOT_ACTIVE"
    case anamnesisNotCompleted = "ANAMNESIS_NOT_COMPLETED"
    case medicalClearanceRequired = "MEDICAL_CLEARANCE_REQUIRED"
    case guardianAuthorizationRequired = "GUARDIAN_AUTHORIZATION_REQUIRED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentPrescriptionEligibilityBlockingReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
