//
// StudentAnamnesisArchiveView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Acervo do **próprio** aluno: todas as versões concluídas de que ele é autor, de todas as suas fichas, com o vínculo de origem de cada uma. Existe para que ele escolha, versão a versão, o que autorizar ao personal atual. Não copia, não importa e não preenche a ficha atual, e não é arquivo profissional. */
public struct StudentAnamnesisArchiveView: Codable, JSONEncodable, Hashable {

    public static let versionsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    /** Da mais recente para a mais antiga. Vazio quando a conta nunca concluiu uma ficha. */
    public var versions: Set<StudentAnamnesisArchiveVersionRef>

    public init(versions: Set<StudentAnamnesisArchiveVersionRef>) {
        self.versions = versions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case versions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(versions, forKey: .versions)
    }
}
