//
// StudentWorkoutSessionHistoryPage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** O histórico de treinos feitos, em uma página por cursor ou com todas as sessões de um intervalo. &#x60;items&#x60; vem do mais recente ao mais antigo (&#x60;startedAt&#x60;); o cliente não reordena, não insere sessão local e **não soma contagens entre páginas**. Com &#x60;from&#x60; e &#x60;to&#x60; a resposta é o intervalo inteiro e &#x60;nextCursor&#x60; é sempre nulo. Lista vazia é \&quot;nenhum treino neste recorte\&quot;, nunca erro nem indisponibilidade; o estado de quem nunca treinou é &#x60;firstSessionOn&#x60; nulo, e não a lista vazia. */
public struct StudentWorkoutSessionHistoryPage: Codable, JSONEncodable, Hashable {

    public static let itemsRule = ArrayRule(minItems: nil, maxItems: 500, uniqueItems: false)
    public static let nextCursorRule = StringRule(minLength: 1, maxLength: 512, pattern: "/^[A-Za-z0-9_-]+$/")
    /** Os treinos do recorte. No modo por cursor, no máximo `limit` (até 50); no modo de intervalo, todos os do intervalo, e o teto do esquema é só de segurança. */
    public var items: [StudentWorkoutSessionHistoryItem]
    /** Cursor opaco da próxima página, **nulo na última** e sempre nulo no modo de intervalo. Nunca é offset, índice ou dado a ser interpretado pelo cliente; é base64url, sem espaço nem pontuação. */
    public var nextCursor: String?
    /** A data civil (`localDate`) da primeira sessão do aluno que entra no histórico, em qualquer modo e sem depender de `from`, `to` nem do cursor: o limite inferior da navegação de mês. **Nulo** é o estado de quem nunca treinou. */
    public var firstSessionOn: Date?

    public init(items: [StudentWorkoutSessionHistoryItem], nextCursor: String?, firstSessionOn: Date?) {
        self.items = items
        self.nextCursor = nextCursor
        self.firstSessionOn = firstSessionOn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case nextCursor
        case firstSessionOn
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(nextCursor, forKey: .nextCursor)
        try container.encode(firstSessionOn, forKey: .firstSessionOn)
    }
}
