//
// StudentTodayLastSessionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Última sessão concluída do aluno, com referência, rótulo e instante, para o card \&quot;última sessão\&quot; da tela. Fato registrado: não é recalculado nem reescrito por uma prescrição publicada depois. Nula quando o aluno ainda não concluiu nenhuma sessão — ausência explícita, nunca zero inventado. */
public struct StudentTodayLastSessionView: Codable, JSONEncodable, Hashable {

    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutFocusRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let versionLabelRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var sessionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var workoutId: String
    /** Nome do treino executado {ex. \"Treino C\"}, como estava na versão que originou a sessão. Conteúdo do domínio preservado verbatim. */
    public var workoutName: String
    /** Foco do treino executado {ex. \"Pernas\"}. Conteúdo autorado preservado verbatim e invariante de locale. Nulo somente quando a sessão referencia uma versão publicada antes de o foco autorado existir. */
    public var workoutFocus: String?
    /** Rótulo da versão da prescrição que originou a sessão, preservado como estava no momento da execução. Código de máquina, nunca localizado. */
    public var versionLabel: String
    /** Instante de conclusão da sessão, com offset explícito. */
    public var completedAt: Date

    public init(sessionId: String, workoutId: String, workoutName: String, workoutFocus: String?, versionLabel: String, completedAt: Date) {
        self.sessionId = sessionId
        self.workoutId = workoutId
        self.workoutName = workoutName
        self.workoutFocus = workoutFocus
        self.versionLabel = versionLabel
        self.completedAt = completedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case workoutId
        case workoutName
        case workoutFocus
        case versionLabel
        case completedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(workoutName, forKey: .workoutName)
        try container.encode(workoutFocus, forKey: .workoutFocus)
        try container.encode(versionLabel, forKey: .versionLabel)
        try container.encode(completedAt, forKey: .completedAt)
    }
}
