//
// StudentTodayWorkoutCardView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Card principal independente; estado explícito e payloads anuláveis coerentes com ele. &#x60;sequencePlan&#x60; existe **somente** quando a ativação vigente é em sequência livre, e então o estado nunca é &#x60;REST_DAY&#x60;. */
public struct StudentTodayWorkoutCardView: Codable, JSONEncodable, Hashable {

    public var status: StudentTodayStatus
    public var prescribedWorkout: StudentTodayPrescribedWorkoutView?
    public var openSession: StudentTodayOpenSessionView?
    public var sequencePlan: StudentTodaySequencePlanView?

    public init(status: StudentTodayStatus, prescribedWorkout: StudentTodayPrescribedWorkoutView?, openSession: StudentTodayOpenSessionView?, sequencePlan: StudentTodaySequencePlanView? = nil) {
        self.status = status
        self.prescribedWorkout = prescribedWorkout
        self.openSession = openSession
        self.sequencePlan = sequencePlan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case prescribedWorkout
        case openSession
        case sequencePlan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(prescribedWorkout, forKey: .prescribedWorkout)
        try container.encode(openSession, forKey: .openSession)
        try container.encodeIfPresent(sequencePlan, forKey: .sequencePlan)
    }
}


extension StudentTodayWorkoutCardView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
