//
// StudentAnamnesisState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado da anamnese funcional. &#x60;COMPLETED&#x60; afirma apenas que existe ao menos uma versão concluída; não afirma elegibilidade para prescrição. */
public enum StudentAnamnesisState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case noAnamnesis = "NO_ANAMNESIS"
    case inProgress = "IN_PROGRESS"
    case completed = "COMPLETED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentAnamnesisState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
