//
// StudentReadinessQuestionKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Chave estável de cada pergunta da triagem. O enunciado exibido pertence à versão licenciada do instrumento e é resolvido fora deste contrato. */
public enum StudentReadinessQuestionKey: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case cardiacOrHypertensionDiagnosis = "CARDIAC_OR_HYPERTENSION_DIAGNOSIS"
    case chestPain = "CHEST_PAIN"
    case balanceLossOrUnconsciousness = "BALANCE_LOSS_OR_UNCONSCIOUSNESS"
    case otherChronicCondition = "OTHER_CHRONIC_CONDITION"
    case chronicConditionMedication = "CHRONIC_CONDITION_MEDICATION"
    case boneJointOrSoftTissueProblem = "BONE_JOINT_OR_SOFT_TISSUE_PROBLEM"
    case supervisedActivityAdvice = "SUPERVISED_ACTIVITY_ADVICE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension StudentReadinessQuestionKey: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
