//
// StudentTodayOpenSessionView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Sessão iniciada e ainda não encerrada, presente se e somente se &#x60;status&#x60; é &#x60;SESSION_IN_PROGRESS&#x60;. Existe para que a tela leve à retomada da sessão aberta em vez de oferecer um novo início. Não transporta execução: série, carga, repetição, alvo, descanso e progresso chegam pelo Workout Core. */
public struct StudentTodayOpenSessionView: Codable, JSONEncodable, Hashable {

    public static let sessionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** A identidade criada no device e adotada pelo servidor no início da sessão; a mesma usada pelo transporte de sync. */
    public var sessionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var workoutId: String
    /** Versão fixada da prescrição; imutável pelo resto da vida da sessão. */
    public var prescriptionVersionId: String
    /** Reutiliza o estado publicado pelo início de sessão. Uma sessão encerrada não aparece aqui: ela é `lastSession` ou nada. */
    public var status: WorkoutSessionStatus
    /** O instante declarado pelo cliente no início, preservado como recebido. */
    public var startedAt: Date

    public init(sessionId: String, workoutId: String, prescriptionVersionId: String, status: WorkoutSessionStatus, startedAt: Date) {
        self.sessionId = sessionId
        self.workoutId = workoutId
        self.prescriptionVersionId = prescriptionVersionId
        self.status = status
        self.startedAt = startedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case workoutId
        case prescriptionVersionId
        case status
        case startedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(prescriptionVersionId, forKey: .prescriptionVersionId)
        try container.encode(status, forKey: .status)
        try container.encode(startedAt, forKey: .startedAt)
    }
}


extension StudentTodayOpenSessionView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
