//
// StudentAnamnesisGoalSection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Objetivo principal e prazo esperado, declarados pelo aluno. */
public struct StudentAnamnesisGoalSection: Codable, JSONEncodable, Hashable {

    public static let otherGoalRule = StringRule(minLength: 1, maxLength: 80, pattern: "/^(?!\\s*(?:[-+>]|[0-9]+\\.)\\s)(?!.*(?:[*_`#\\[\\]<>|]|---)).+$/")
    public var sectionKey: String
    public var primaryGoal: StudentTrainingGoal
    /** Texto após trim, sem Markdown ou HTML; exigido com `primaryGoal: OTHER` e proibido sem ele — a regra é do schema, não da prosa. */
    public var otherGoal: String?
    public var expectedTimeframe: StudentGoalTimeframe

    public init(sectionKey: String, primaryGoal: StudentTrainingGoal, otherGoal: String? = nil, expectedTimeframe: StudentGoalTimeframe) {
        self.sectionKey = sectionKey
        self.primaryGoal = primaryGoal
        self.otherGoal = otherGoal
        self.expectedTimeframe = expectedTimeframe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sectionKey
        case primaryGoal
        case otherGoal
        case expectedTimeframe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sectionKey, forKey: .sectionKey)
        try container.encode(primaryGoal, forKey: .primaryGoal)
        try container.encodeIfPresent(otherGoal, forKey: .otherGoal)
        try container.encode(expectedTimeframe, forKey: .expectedTimeframe)
    }
}


extension StudentAnamnesisGoalSection: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if primaryGoal == .unknownDefaultOpenApi { return true }
        if expectedTimeframe == .unknownDefaultOpenApi { return true }
        return false
    }
}

/// Prevent credentials and identity proofs from leaking through logs.
extension StudentAnamnesisGoalSection: CustomStringConvertible {
    public var description: String { "StudentAnamnesisGoalSection([REDACTED])" }
}
