//
// StudentOnboardingNextAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Próxima ação decidida pelo servidor. Ela nunca é &#x60;AGUARDAR AUTORIZAÇÃO DE RESPONSÁVEL&#x60;: autorização de responsável não interrompe a conclusão. */
public struct StudentOnboardingNextAction: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case startStudentAnamnesis = "START_STUDENT_ANAMNESIS"
        case continueStudentAnamnesis = "CONTINUE_STUDENT_ANAMNESIS"
        case completeStudentAnamnesis = "COMPLETE_STUDENT_ANAMNESIS"
        case awaitPrescription = "AWAIT_PRESCRIPTION"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var targetSectionKey: StudentAnamnesisSectionKey?

    public init(type: ModelType, targetSectionKey: StudentAnamnesisSectionKey? = nil) {
        self.type = type
        self.targetSectionKey = targetSectionKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case targetSectionKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(targetSectionKey, forKey: .targetSectionKey)
    }
}


extension StudentOnboardingNextAction: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if targetSectionKey == .unknownDefaultOpenApi { return true }
        return false
    }
}
