//
// StudentTodayPersonalRef.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Referência mínima à autoria da prescrição: identidade opaca mais o nome autorado. Pode apontar para um personal anterior e por isso não carrega a projeção atual de avatar nem de registro profissional. */
public struct StudentTodayPersonalRef: Codable, JSONEncodable, Hashable {

    public static let personalIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let displayNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var personalId: String
    /** Nome autorado preservado verbatim UTF-8. Nunca traduzido, reescrito, truncado nem usado como chave de mensagem. */
    public var displayName: String

    public init(personalId: String, displayName: String) {
        self.personalId = personalId
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case personalId
        case displayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(personalId, forKey: .personalId)
        try container.encode(displayName, forKey: .displayName)
    }
}
