//
// SubstitutionScope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Alcance declarado da substituição dentro da sessão. Carga nunca é transportada automaticamente entre variantes ou equipamentos, qualquer que seja o escopo. */
public enum SubstitutionScope: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case thisSet = "THIS_SET"
    case remainingSets = "REMAINING_SETS"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SubstitutionScope: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
