//
// SubstitutionSyncView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubstitutionSyncView: Codable, JSONEncodable, Hashable {

    public enum ViewType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case substitution = "SUBSTITUTION"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let substitutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let exerciseExecutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedExerciseIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescribedVariantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let executedExerciseIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let executedVariantIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var viewType: ViewType
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var substitutionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var exerciseExecutionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var prescribedExerciseId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var prescribedVariantId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var executedExerciseId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var executedVariantId: String
    public var type: SubstitutionType
    public var reason: SubstitutionReason
    public var authorizationSource: SubstitutionAuthorizationSource
    public var scope: SubstitutionScope
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var registeredAt: Date

    public init(viewType: ViewType, substitutionId: String, exerciseExecutionId: String, prescribedExerciseId: String, prescribedVariantId: String, executedExerciseId: String, executedVariantId: String, type: SubstitutionType, reason: SubstitutionReason, authorizationSource: SubstitutionAuthorizationSource, scope: SubstitutionScope, registeredAt: Date) {
        self.viewType = viewType
        self.substitutionId = substitutionId
        self.exerciseExecutionId = exerciseExecutionId
        self.prescribedExerciseId = prescribedExerciseId
        self.prescribedVariantId = prescribedVariantId
        self.executedExerciseId = executedExerciseId
        self.executedVariantId = executedVariantId
        self.type = type
        self.reason = reason
        self.authorizationSource = authorizationSource
        self.scope = scope
        self.registeredAt = registeredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case viewType
        case substitutionId
        case exerciseExecutionId
        case prescribedExerciseId
        case prescribedVariantId
        case executedExerciseId
        case executedVariantId
        case type
        case reason
        case authorizationSource
        case scope
        case registeredAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(viewType, forKey: .viewType)
        try container.encode(substitutionId, forKey: .substitutionId)
        try container.encode(exerciseExecutionId, forKey: .exerciseExecutionId)
        try container.encode(prescribedExerciseId, forKey: .prescribedExerciseId)
        try container.encode(prescribedVariantId, forKey: .prescribedVariantId)
        try container.encode(executedExerciseId, forKey: .executedExerciseId)
        try container.encode(executedVariantId, forKey: .executedVariantId)
        try container.encode(type, forKey: .type)
        try container.encode(reason, forKey: .reason)
        try container.encode(authorizationSource, forKey: .authorizationSource)
        try container.encode(scope, forKey: .scope)
        try container.encode(registeredAt, forKey: .registeredAt)
    }
}


extension SubstitutionSyncView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if viewType == .unknownDefaultOpenApi { return true }
        if type == .unknownDefaultOpenApi { return true }
        if reason == .unknownDefaultOpenApi { return true }
        if authorizationSource == .unknownDefaultOpenApi { return true }
        if scope == .unknownDefaultOpenApi { return true }
        return false
    }
}
