//
// SubstitutionReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Motivo estruturado da substituição, obrigatório. &#x60;PERSONAL_INSTRUCTION&#x60; preserva a orientação explícita do personal, que é diferente de preferência do aluno e de indisponibilidade de equipamento; aparelho ocupado e aparelho quebrado também permanecem motivos distintos. */
public enum SubstitutionReason: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case equipmentOccupied = "EQUIPMENT_OCCUPIED"
    case equipmentBroken = "EQUIPMENT_BROKEN"
    case equipmentUnavailable = "EQUIPMENT_UNAVAILABLE"
    case preference = "PREFERENCE"
    case discomfort = "DISCOMFORT"
    case personalInstruction = "PERSONAL_INSTRUCTION"
    case other = "OTHER"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SubstitutionReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
