//
// SyncConflictKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Classe determinística do conflito. &#x60;REVISION_STALE&#x60;: &#x60;expectedRevision&#x60; (ou a &#x60;canonicalRevision&#x60; de uma resolução) é anterior à revisão atual. &#x60;IDENTITY_DIVERGENT&#x60;: a mesma identidade (&#x60;commandId&#x60; ou id do fato) chegou com conteúdo diferente; o canônico é o primeiro processamento. &#x60;INVARIANT_VIOLATED&#x60;: transição de lifecycle inválida; o cliente converge para o estado canônico. &#x60;IMMUTABLE_TARGET&#x60;: tentativa de alterar prescrição publicada ou versão fixada da sessão; nunca aceito. Nenhuma classe usa &#x60;clientOccurredAt&#x60; para escolher vencedor. */
public enum SyncConflictKind: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case revisionStale = "REVISION_STALE"
    case identityDivergent = "IDENTITY_DIVERGENT"
    case invariantViolated = "INVARIANT_VIOLATED"
    case immutableTarget = "IMMUTABLE_TARGET"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SyncConflictKind: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
