//
// SyncTombstoneReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Motivo de um &#x60;TOMBSTONE&#x60;, distinto em código de máquina. &#x60;VISIBILITY_ENDED&#x60;: o destinatário perdeu a visibilidade da entidade (reautorização na leitura). &#x60;RETENTION_EXPIRED&#x60;: recorte de retenção do servidor. &#x60;AMENDED&#x60;: o conteúdo anterior foi substituído por emenda auditável; a emenda chega como entidade própria. &#x60;SUPERSEDED&#x60;: versão de prescrição substituída por outra publicada. &#x60;ASSIGNMENT_REMOVED&#x60;: atribuição retirada do escopo do aluno. &#x60;RELATIONSHIP_ENDED&#x60;: vínculo Personal–Aluno encerrado; o ex-personal para de receber fatos do aluno dali em diante e o escopo do próprio aluno não recebe tombstone pelo encerramento. */
public enum SyncTombstoneReason: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case visibilityEnded = "VISIBILITY_ENDED"
    case retentionExpired = "RETENTION_EXPIRED"
    case amended = "AMENDED"
    case superseded = "SUPERSEDED"
    case assignmentRemoved = "ASSIGNMENT_REMOVED"
    case relationshipEnded = "RELATIONSHIP_ENDED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SyncTombstoneReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
