//
// SyncTrigger.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Origem do ciclo de sincronização. &#x60;AUTOMATIC&#x60; para os gatilhos do sync engine (rede voltou, app em foreground, fato novo na fila, intervalo); &#x60;MANUAL&#x60; para o botão de sincronizar. Muda métrica e limite de taxa; não muda prioridade nem representação. */
public enum SyncTrigger: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case automatic = "AUTOMATIC"
    case manual = "MANUAL"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SyncTrigger: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
