//
// SyncCommandResultStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Veredito de um command, fechado em quatro valores que determinam a ação do cliente sem interpretar texto: &#x60;ACKNOWLEDGED&#x60; sai da outbox (inclusive no replay de um command já confirmado); &#x60;RETRYABLE_FAILURE&#x60; permanece na fila e é reenviado com o mesmo &#x60;commandId&#x60; após backoff; &#x60;CONFLICT&#x60; aguarda decisão explícita da pessoa, com a versão canônica preservada; &#x60;FINAL_FAILURE&#x60; não é reenviável e permanece visível, nunca descartado em silêncio. */
public enum SyncCommandResultStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case acknowledged = "ACKNOWLEDGED"
    case retryableFailure = "RETRYABLE_FAILURE"
    case conflict = "CONFLICT"
    case finalFailure = "FINAL_FAILURE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SyncCommandResultStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
