//
// UpdatePrescriptionDraftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Substitui a estrutura do rascunho. &#x60;If-Match&#x60; com a &#x60;revision&#x60; lida é obrigatório: duas edições concorrentes nunca aplicam last-write-wins e a perdedora recebe conflito explícito. */
public struct UpdatePrescriptionDraftRequest: Codable, JSONEncodable, Hashable {

    public var content: PrescriptionDraftContent

    public init(content: PrescriptionDraftContent) {
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
    }
}
