//
// UpdatePlanActivationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Substitui a programação da ativação vigente: o modo, os slots ou a sequência e a data de término. As regras de &#x60;weekdaySlots&#x60;, &#x60;sequence&#x60; e &#x60;endDate&#x60; são as de &#x60;ActivatePlanRequest&#x60;; o início e a versão não se alteram aqui, e &#x60;endDate&#x60; ausente é ativação sem data de término. */
public struct UpdatePlanActivationRequest: Codable, JSONEncodable, Hashable {

    public static let weekdaySlotsRule = ArrayRule(minItems: 1, maxItems: 20, uniqueItems: false)
    public static let sequenceRule = ArrayRule(minItems: 1, maxItems: 20, uniqueItems: false)
    public var mode: PlanActivationMode
    /** Último dia de validade; ausente quando a ativação passa a não ter data de término. Nunca anterior ao início. */
    public var endDate: Date?
    /** Programação por dias da semana, um slot por treino; só em `WEEKDAYS`. */
    public var weekdaySlots: [PlanWeekdaySlot]?
    /** Ordem dos treinos em sequência livre; só em `SEQUENCE`. Lista ordenada, sem repetição de treino. */
    public var sequence: [String]?

    public init(mode: PlanActivationMode, endDate: Date? = nil, weekdaySlots: [PlanWeekdaySlot]? = nil, sequence: [String]? = nil) {
        self.mode = mode
        self.endDate = endDate
        self.weekdaySlots = weekdaySlots
        self.sequence = sequence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mode
        case endDate
        case weekdaySlots
        case sequence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mode, forKey: .mode)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(weekdaySlots, forKey: .weekdaySlots)
        try container.encodeIfPresent(sequence, forKey: .sequence)
    }
}


extension UpdatePlanActivationRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if mode == .unknownDefaultOpenApi { return true }
        return false
    }
}
