//
// VerifyOtpChallengeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyOtpChallengeRequest: Codable, JSONEncodable, Hashable {

    public static let codeRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[0-9]{6,8}$/")
    /** Código numérico de uso único com o tamanho emitido pelo provedor. */
    public var code: String
    public var device: DeviceContext

    public init(code: String, device: DeviceContext) {
        self.code = code
        self.device = device
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case device
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(device, forKey: .device)
    }
}


/// Prevent credentials and identity proofs from leaking through logs.
extension VerifyOtpChallengeRequest: CustomStringConvertible {
    public var description: String { "VerifyOtpChallengeRequest([REDACTED])" }
}
