//
// WorkoutAssignmentView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Atribuição de um treino de versão publicada a uma data civil do aluno. Referencia a versão por identidade e nunca copia o conteúdo prescrito para o dia. */
public struct WorkoutAssignmentView: Codable, JSONEncodable, Hashable {

    public static let assignmentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let studentIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let prescriptionVersionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let workoutIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let activationIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var assignmentId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var studentId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var prescriptionVersionId: String
    /** Identificador público opaco. O cliente não deve inferir semântica, ordem ou tipo interno. */
    public var workoutId: String
    /** Data civil no calendário ISO 8601, sem horário ou timezone. */
    public var localDate: Date
    public var status: WorkoutAssignmentStatus
    /** Revisão opaca definida pelo servidor. O cliente compara somente por igualdade, nunca infere ordem e nunca a cria; `expectedRevision` e `canonicalRevision` apenas ecoam um valor lido do servidor. */
    public var revision: String
    /** Ativação que materializou esta atribuição; ausente quando o personal a fez à mão (`assignPersonalStudentWorkout`). Só a atribuição materializada por uma ativação é retirada quando ela é substituída, alterada ou encerrada: a do ajuste de um dia permanece. */
    public var activationId: String?

    public init(assignmentId: String, studentId: String, prescriptionVersionId: String, workoutId: String, localDate: Date, status: WorkoutAssignmentStatus, revision: String, activationId: String? = nil) {
        self.assignmentId = assignmentId
        self.studentId = studentId
        self.prescriptionVersionId = prescriptionVersionId
        self.workoutId = workoutId
        self.localDate = localDate
        self.status = status
        self.revision = revision
        self.activationId = activationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assignmentId
        case studentId
        case prescriptionVersionId
        case workoutId
        case localDate
        case status
        case revision
        case activationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assignmentId, forKey: .assignmentId)
        try container.encode(studentId, forKey: .studentId)
        try container.encode(prescriptionVersionId, forKey: .prescriptionVersionId)
        try container.encode(workoutId, forKey: .workoutId)
        try container.encode(localDate, forKey: .localDate)
        try container.encode(status, forKey: .status)
        try container.encode(revision, forKey: .revision)
        try container.encodeIfPresent(activationId, forKey: .activationId)
    }
}


extension WorkoutAssignmentView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
