//
// WorkoutTemplateView.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Modelo de treino do personal: um plano sem aluno. O conteúdo é o mesmo &#x60;PrescriptionDraftContent&#x60; do rascunho — o nome do modelo é &#x60;content.name&#x60; — e o resto são os metadados da biblioteca. &#x60;revision&#x60; é a revisão opaca do servidor, ecoada em &#x60;If-Match&#x60; na edição e no arquivamento; o cliente nunca a cria. O modelo não tem estado de publicação, versão, aluno nem carga de referência, e **não tem command de sync**. */
public struct WorkoutTemplateView: Codable, JSONEncodable, Hashable {

    public static let templateIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let descriptionRule = StringRule(minLength: 1, maxLength: 500, pattern: nil)
    public static let tagsRule = ArrayRule(minItems: nil, maxItems: 10, uniqueItems: false)
    public static let revisionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Identidade do modelo, criada pelo personal no device. */
    public var templateId: String
    /** Descrição do modelo, autorada pelo personal e preservada verbatim UTF-8; ausente quando o personal não a escreveu. */
    public var description: String?
    /** Etiquetas do modelo, até dez, **na ordem em que o personal as escreveu**, que o servidor preserva. Uma etiqueta repetida — ignorando caixa e acento — é `422 VALIDATION_FAILED` no pedido, sem gravar. A lista não declara `uniqueItems` de propósito: o gerador a transformaria em conjunto não ordenado nos clientes, e a ordem das etiquetas é do personal. Ausente no pedido é nenhuma etiqueta. */
    public var tags: [String]
    public var goal: WorkoutTemplateGoal?
    public var level: WorkoutTemplateLevel?
    /** Revisão opaca do servidor; comparada somente por igualdade e nunca inferida pelo cliente. */
    public var revision: String
    /** Instante RFC 3339 / ISO 8601 com offset explícito. */
    public var updatedAt: Date
    public var content: PrescriptionDraftContent

    public init(templateId: String, description: String? = nil, tags: [String], goal: WorkoutTemplateGoal? = nil, level: WorkoutTemplateLevel? = nil, revision: String, updatedAt: Date, content: PrescriptionDraftContent) {
        self.templateId = templateId
        self.description = description
        self.tags = tags
        self.goal = goal
        self.level = level
        self.revision = revision
        self.updatedAt = updatedAt
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templateId
        case description
        case tags
        case goal
        case level
        case revision
        case updatedAt
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(templateId, forKey: .templateId)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(tags, forKey: .tags)
        try container.encodeIfPresent(goal, forKey: .goal)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encode(revision, forKey: .revision)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(content, forKey: .content)
    }
}


extension WorkoutTemplateView: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if goal == .unknownDefaultOpenApi { return true }
        if level == .unknownDefaultOpenApi { return true }
        return false
    }
}
