//
// WorkoutAssignmentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Estado da atribuição. &#x60;RETIRED&#x60; é fato registrado e continua presente na projeção — o cliente distingue atribuição ausente de atribuição retirada, e retirar nunca vira marca de remoção nem apaga sessão histórica. */
public enum WorkoutAssignmentStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case available = "AVAILABLE"
    case retired = "RETIRED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension WorkoutAssignmentStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
